In [5]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.6-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.5.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tarkeshwar\desktop\abhishek\technical skills\tutedude\gen ai\generative-artificial-intelligence\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\tarkeshwar\desktop\abhishek\technical skills\tutedude\gen ai\generative-artificial-intelligence\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.6-cp313-cp313-win_amd64.whl (9.6 MB)
Using cached numpy-2.5.3-cp313-cp313-win_amd64.whl (12.6 MB)
Using cached tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.5.3 pandas-3.0.6 tzdata-2026.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import numpy as np
import pandas as pd

## Pandas Series is a column of data in a table like in excel or google sheets with labels called as indexes attached to each value.

In [2]:
pd.Series(data=[40,50,60], index=['Bread','Milk','Butter'])

Bread     40
Milk      50
Butter    60
dtype: int64

In [3]:
pd.Series(data=[40,50,60], index=['Bread','Milk','Butter'], name='Price of grocery items')

Bread     40
Milk      50
Butter    60
Name: Price of grocery items, dtype: int64

#### Series is a 1-d array that can hold any type of data like integers, floats, boolean, string (objects), mixed data types

## Data type ---> integers --> data in a Series (column) --> Quantity of items in the stock
## Data type ---> Float ---> data in a Series (column) ---> Price or product ratings
## Data type ---> String --> data in a Series (column) ---> Product name
## Data type ---> boolean --> data in a Series (column) ---> Is item in stock ?
## Data type ---> Data/ Time --> data in a Series (column) ---> Expiry dates or sale dates
## Mixed type ---> Milk, 40, True

## Creating a Series in Multiple ways :-
#### 1. List
#### 2. NumPy array
#### 3. Dictionary
#### 4. Custom index
#### 5. Scalar value

In [4]:
## Series from list:-

country=['India','China','USA','Pakistan']

pd.Series(country)

0       India
1       China
2         USA
3    Pakistan
dtype: str

In [5]:
batsman_runs = [48,64,72,98,114,183]


pd.Series(batsman_runs)
# pd.Series(batsman_runs, dtype='int32')

0     48
1     64
2     72
3     98
4    114
5    183
dtype: int64

In [6]:
subject_names = ['Maths','Physics','Chemistry','Biology','English']

subject_marks = [48,92,64,35,98]

pd.Series(data=subject_marks, index=subject_names, name='Subject marks data', dtype='int32')

Maths        48
Physics      92
Chemistry    64
Biology      35
English      98
Name: Subject marks data, dtype: int32

In [7]:
### Creating a Series using a NumPy array

values = np.arange(10,21)
pd.Series(values)

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

In [8]:
## Dictionary to Series

## Dictionary is another data structure that stores the data in a key:value pair and 
## just because it stores the data in a key:value pair so we don't have to explicitly mention the index.

In [9]:
data_items = {'Marks':78, 'English':92, 'Physics':88, 'Chemistry':64}
pd.Series(data_items)

Marks        78
English      92
Physics      88
Chemistry    64
dtype: int64

In [10]:
## custom index to series

values = [1,2,3,4,5]
pd.Series(data=values, index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
## Scalar value inside a Series 

pd.Series(4,index=['a','b','c','d','e'])

a    4
b    4
c    4
d    4
e    4
dtype: int64

## read_csv() ---> 90% is being used --> this function reads the content from the csv file in pandas dataframe format so that we can perform the operations on the data or we can perform effective analysis.

In [12]:
Data = pd.read_csv('C:/Users/Tarkeshwar/Desktop/ABHISHEK/Technical skills/Tutedude/Gen AI/Generative-Artificial-Intelligence/Machine Learning/Prerequisites/Module 8_Pandas/Pandas/youtube_2025_dataset_202504061614.csv')

In [13]:
Data

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [14]:
# 2nd way to read
df = pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [15]:
df

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [16]:
## DataFrame --> Combination of multiple Series (Series means a single column)

In [17]:
## converting data frame to Series --> use squeeze parameter --> it make sure that the data is in Series format

In [18]:
pd.read_csv('youtube_one_column.csv')

                     Channel Name
0                 Smith-Ross Labs
1                Sandoval PLC Hub
2     Jones, Moore and Ho Network
3            Mitchell-Hooper Labs
4              Wilson LLC Studios
...                           ...
4995        Flores-Daniel Studios
4996     Spencer and Sons Studios
4997       Obrien-Roberts Studios
4998                 King Ltd Hub
4999            Henry Ltd Studios

[5000 rows x 1 columns]

In [19]:
type(pd.read_csv('youtube_one_column.csv'))

pandas.DataFrame

In [20]:
## to convert data frame into Series :-

df = pd.read_csv('youtube_one_column.csv').squeeze('columns')

In [21]:
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

In [22]:
type(df)

pandas.Series

In [23]:
pd.read_csv('youtube_two_column.csv')

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [24]:
## index_col

In [25]:
dataframe = pd.read_csv('youtube_two_column.csv', index_col='Youtuber Name').squeeze('columns')

In [26]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [27]:
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

### Attribute in Series

### 1) .values --> representing only the values of the given series
### 2) .index --> returns only the index values from the given column
### 3) .dtype --> it provides the idea about the data type of the values that you are storing
### 4) .size --> this attribute provides the idea about the total number of rows inside the dataset
### 5) .shape --> this attribute provides the idea about the row, column information
### 6) .ndim --> this attribute provides the idea about the dimention of the given dataset
### 7) .name --> this attribute provides the idea about the name of the series
### 8) .is_unique --> this provides us with the idea about whether if unique values are there or not inside the column

In [28]:
df.values

<StringArray>
[                    'Smith-Ross Labs',                    'Sandoval PLC Hub',
         'Jones, Moore and Ho Network',                'Mitchell-Hooper Labs',
                  'Wilson LLC Studios',                   'Myers Ltd Network',
                   'Huber Inc Network',              'Baxter-Collins Studios',
                   'Morrow-Abbott Hub',               'Jackson Group Network',
 ...
                     'Cole-Sharp Labs', 'Sherman, Mcgee and Phillips Studios',
                      'Baker-Hill Hub',    'Francis, Davis and Jones Network',
     'Whitaker, Horn and Escobar Labs',               'Flores-Daniel Studios',
            'Spencer and Sons Studios',              'Obrien-Roberts Studios',
                        'King Ltd Hub',                   'Henry Ltd Studios']
Length: 5000, dtype: str

In [29]:
dataframe.values

array([ 68, 128, 282, ..., 179, 182,  92], shape=(5000,))

In [30]:
dataframe.index

Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='str', name='Youtuber Name', length=5000)

In [31]:
dataframe.dtype

dtype('int64')

In [32]:
df.dtype

In [33]:
dataframe = dataframe.astype('int32')

In [34]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [35]:
dataframe.size

5000

In [36]:
dataframe.shape

(5000,)

In [37]:
dataframe.ndim

1

In [38]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [39]:
dataframe.name

'Total Videos'

In [40]:
dataframe.is_unique

False

In [41]:
pd.Series([1,2,3,4,5]).is_unique

True

## Series methods

#### 1) head() ---> provides the top preview of data as the top 5 rows of the dataframe or Series. It is quite helpful with providing the preview of the dataset and if we want to preview top 10 rows then we can pass 10 as the argument or for top 7 rows we can pass 7 as an argument. 

#### 2) tail() ---> provides the bottom preview of data as the bottom 5 rows

#### for e.g. --> dataset --> salary column --> top 5 rows --> salary --> 7 lpa ---> top 10 ---> top 15 ,,, tail() ---> bottom 5 rows ---> salary --> 4 lpa, 9 lpa

#### 3) sample() --> provides any custom row from the dataset for us to preview it.

#### 4) value_counts() --> it provides the idea about the count of the values (categorical values), if i am having a column where the categorical value count i want to calculate then i can go with value_counts()

#### 5) sort_values() --> this method sorts the value in an ascending manner. It can be useful for us for the numerical columns. you can even sort the values in descending manner as well.

#### 6) sort_index() --> this method sorts the index of the dataset.

In [42]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [43]:
dataframe.head()

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Name: Total Videos, dtype: int32

In [44]:
dataframe.head(9)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Anna Berry             98
Richard Arnold        494
Stephanie Potter      133
Teresa Aguirre        316
Name: Total Videos, dtype: int32

In [45]:
dataframe.head(21)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Anna Berry             98
Richard Arnold        494
Stephanie Potter      133
Teresa Aguirre        316
Anne Adkins           140
David Clark            52
Kathleen Weeks        149
Melissa Kennedy        53
Kimberly Brown        299
Jennifer Martinez     383
Elizabeth Wright       79
Elijah Ruiz           373
Thomas Roberts         59
Julian Gutierrez      500
Sheila Rivera         332
Crystal Vargas        133
Name: Total Videos, dtype: int32

In [46]:
dataframe.tail()

Youtuber Name
Jasmine Smith     106
John Rasmussen    130
Lisa Burke        179
Steve Diaz        182
Austin Tate        92
Name: Total Videos, dtype: int32

In [47]:
df.head()

0                Smith-Ross Labs
1               Sandoval PLC Hub
2    Jones, Moore and Ho Network
3           Mitchell-Hooper Labs
4             Wilson LLC Studios
Name: Channel Name, dtype: str

In [48]:
df.tail()

4995       Flores-Daniel Studios
4996    Spencer and Sons Studios
4997      Obrien-Roberts Studios
4998                King Ltd Hub
4999           Henry Ltd Studios
Name: Channel Name, dtype: str

In [49]:
df.tail(11)

4989                   Knight and Sons Labs
4990                        Cole-Sharp Labs
4991    Sherman, Mcgee and Phillips Studios
4992                         Baker-Hill Hub
4993       Francis, Davis and Jones Network
4994        Whitaker, Horn and Escobar Labs
4995                  Flores-Daniel Studios
4996               Spencer and Sons Studios
4997                 Obrien-Roberts Studios
4998                           King Ltd Hub
4999                      Henry Ltd Studios
Name: Channel Name, dtype: str

In [50]:
df.sample()

1958    Walker and Sons Studios
Name: Channel Name, dtype: str

In [51]:
df.sample(5)

1354    Johnson-Scott Network
2242      Johnson PLC Studios
522       Huffman-Hodges Labs
1262      Pennington Ltd Labs
255          Lee and Sons Hub
Name: Channel Name, dtype: str

In [52]:
youtube = pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [53]:
youtube

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [54]:
avg = youtube['Avg Video Length (min)']

In [55]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [56]:
type(avg)

pandas.Series

In [57]:
avg.value_counts()

Avg Video Length (min)
24.1    276
23.8    264
23.9    256
24.2    253
24.0    251
       ...
19.9      1
27.3      1
28.0      1
21.0      1
20.7      1
Name: count, Length: 78, dtype: int64

In [58]:
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

In [59]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [60]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [61]:
## parameter --> ascending = False (sorting --? descending)

avg.sort_values(ascending=False)

361     28.9
1467    28.4
364     28.3
925     28.1
2748    28.0
        ...
3704    20.7
171     20.6
1713    19.9
451     19.3
500     19.1
Name: Avg Video Length (min), Length: 5000, dtype: float64

## Method chaining --> we will use multiple methods together to get the required value in a way the first method's output will be second method's input then second's method output will be third method's input

In [62]:
avg.sort_values(ascending=False).head(1)

361    28.9
Name: Avg Video Length (min), dtype: float64

In [63]:
avg.sort_values(ascending=False).head(1).values[0]

np.float64(28.9)

In [64]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [65]:
### In order to make a change in your data permanent --> inplace parameter

In [66]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [67]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [68]:
avg.sort_values(inplace=True)

In [69]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [70]:
average_data = avg.copy

In [71]:
average_data

<bound method NDFrame.copy of 500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64>

In [72]:
average_data

<bound method NDFrame.copy of 500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64>

In [73]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [74]:
dataframe.sort_index()

Youtuber Name
Aaron Archer        136
Aaron Bishop        151
Aaron Brown          51
Aaron Burns         314
Aaron Carrillo      210
                   ...
Zachary Phillips    478
Zachary Russell      81
Zachary Shelton     446
Zoe Peterson         78
Zoe Smith            83
Name: Total Videos, Length: 5000, dtype: int32

In [75]:
youtube = pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [76]:
youtube

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [77]:
subs = youtube['Total Subscribers']

In [78]:
subs

0       8264152
1       8768222
2       6163386
3       4712268
4       9592017
         ...
4995    2665835
4996     136992
4997    2314561
4998    6954832
4999    6785166
Name: Total Subscribers, Length: 5000, dtype: int64

### Mathematical functions in Pandas

#### 1) sum() --> sum of all values present inside the series
#### 2) product() --> product of all values in the series
#### 3) mean() --> provides us with the average value of the data column.
#### for e.g. --> company data --> salary --> average value for that column --> salary = 6,6,8,9,11,,, mean = (6+6+8+9+11)/5 --> 8 LPA

#### median() --> also provides the idea about the average of the data. for coming up with median, we need to sort the values in ascending manner and then the middle value after sorting the data --> median; data ----> salary --> 70 lakh (outlier), ---> avg --> 7+8+6+9+ 

#### mode() --> mode() --> provides us with the idea that which value is getting repeated maximum number of times.

#### std() --> if i need to get thet idea that how the values inside the series are distributed from the average or mean value then we can come up with the standard deviation
#### salary --> 7,8,6,6.5,7.5 --> low standard deviation
#### salary --> 7,15,4,20,28,17 --> high standard deviation

#### variance --> variance also provides the insight about the distribution of the data from the mean value and variance is the square of the standard deviation.
#### standard deviation = (|mean - variance 1| + |mean - variance 2| + ...) / total count of values

#### variance = std**2

#### min() --> minimum value in the series
#### max() --> maximum value in the series


## describe () --> provides the idea about the summary of the important mathematical calculations for the data.

### below ideas we'll be getting after using describe function
#### min --> minimum value
#### max --> maximum value
#### mean --> average value
#### std --> standard deviation
#### 25%ile --> 25% of the values out of my all values are less than this specific value
#### 50% --> 50% of the values out of my all values are less than this specific value
#### 75% --> 75% of the values out of my all values are less than this specific value
#### count ----> total number of rows in the column

#### JEE Mains --> 25% --> my score in JEE Mains was greater than 25% of the total applicants who applied in JEE

In [79]:
subs.sum()

np.int64(25292407967)

In [80]:
subs.product()

np.int64(0)

In [81]:
subs.mean()

np.float64(5058481.5934)

In [82]:
subs.median()

np.float64(5105967.0)

In [83]:
subs.mode()

0          1755
1          2910
2          8649
3          9029
4          9436
         ...
4995    9991900
4996    9992512
4997    9995049
4998    9999559
4999    9999975
Name: Total Subscribers, Length: 5000, dtype: int64

In [84]:
avg.mode()

0    24.1
Name: Avg Video Length (min), dtype: float64

In [85]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [86]:
avg.std()

np.float64(0.8745549483431755)

In [87]:
avg.var()

np.float64(0.7648463576715343)

In [88]:
avg.min()

np.float64(19.1)

In [89]:
avg.max()

np.float64(28.9)

In [90]:
avg.describe()

count    5000.000000
mean       24.004540
std         0.874555
min        19.100000
25%        23.500000
50%        24.000000
75%        24.500000
max        28.900000
Name: Avg Video Length (min), dtype: float64

### Indexing in series (to have the access over the certain value or values)

#### 1) Positive indexing (just like list) --> starts from 0 to forward direction
#### 2) NO Negative indexing 
#### 3) Slicing --> In series we can get the certain values over a given specific range and we can do it using [initial_value, final_value + 1]

#### 4) Fancy indexing --> If i want the specific value from the series then we go with fancy indexing

#### 5) Indexing with labels --> A series which is consisting of labels as the index or custom index, then for this data we can retrieve the info using that custom index or label

In [91]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [92]:
avg[0]

np.float64(24.8)

In [93]:
avg[5]

np.float64(24.2)

In [94]:
## avg[-1] error

In [95]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [96]:
avg[7:18]

3954    20.9
3627    21.0
210     21.1
1511    21.2
2529    21.3
3105    21.3
3924    21.3
1896    21.3
3710    21.3
1526    21.4
3499    21.4
Name: Avg Video Length (min), dtype: float64

In [97]:
### If i want the values skipped as a certain value

avg[2:21:2]

1713    19.9
3704    20.7
3456    20.9
3627    21.0
1511    21.2
3105    21.3
1896    21.3
1526    21.4
2705    21.4
3347    21.4
Name: Avg Video Length (min), dtype: float64

In [98]:
### Reverse values in a Series

avg[::-1]

361     28.9
1467    28.4
364     28.3
925     28.1
2748    28.0
        ...
3704    20.7
171     20.6
1713    19.9
451     19.3
500     19.1
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [99]:
avg[[2,4,9]]

2    24.0
4    24.6
9    24.2
Name: Avg Video Length (min), dtype: float64

In [100]:
avg[[55,1008,79,56,65]]

55      24.9
1008    23.3
79      25.1
56      23.0
65      25.8
Name: Avg Video Length (min), dtype: float64

In [101]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [102]:
dataframe['Steve Diaz']

np.int32(182)

In [103]:
dataframe['Jasmine Smith']

Youtuber Name
Jasmine Smith    244
Jasmine Smith    418
Jasmine Smith    106
Name: Total Videos, dtype: int32

## Editing series (Bring the changes into the values stored inside the series)

#### 1) Using Indexing  --> df[0]=65 ----> changing the original value at index 0 to 65

In [104]:
dataframe['Cynthia Harrington'] = 75

In [105]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [106]:
### I findexing doesn't exist 
dataframe['Amit Kumar Singh'] = 78

In [107]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int32

In [108]:
## Slicing in Series --> df[2:7]=100 --> 100 value will be associated for index 2 to 6

In [109]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int32

In [110]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [111]:
avg[1:5] = 28

In [112]:
avg

500     19.1
451     28.0
1713    28.0
171     28.0
3704    28.0
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [113]:
## Fancy indexing --> df[2,4,8] = [45, 84, 79]

In [114]:
avg[[4,4998,4996,0]] = [25,21,20,24]

In [115]:
avg

500     19.1
451     28.0
1713    28.0
171     28.0
3704    28.0
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [116]:
## Indexing labelling

dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int32

In [117]:
dataframe['Eric Patel', 'Jessica Nelson MD', 'Amit Kumar Singh'] = [45,250,100]

IndexingError: Too many indexers

# Machine Learning Lifecycle

## Data gathering (storing it into a dataframe)
##              ||
## Data exploration
##              ||
## Data cleaning
##              ||
## Exploratory data analysis (Pandas, Matplotlib, Seaborn)
##              ||
## Data processing
##              ||
## Machine learning models

### Data Frame --> for reading the content from the tabular data or the data that is stored in a 2-d structure or in rows and column format or consisting of multiple series in combination, we require data frame and on the pandas data frame we can have the functions to explore and to perform manupulations and analysis on the data we are going to store inside it.

### Series with Python Functionalities

#### len --> It provides the idea with total number of elements present in the series

#### type --> It provides the idea about the data type in the series

#### dir --> It provides with the idea about all of the methods and attributes associated with the series

#### sorted() --> It sorts the value in ascending manner

#### max --> it calculates the max value in the series

#### min --> it calculates the min value in the series

In [118]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int32

In [119]:
len(dataframe)

5001

In [120]:
type(dataframe)

pandas.Series

In [121]:
dir(dataframe)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'between',
 'between_time',
 'bfill',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [122]:
avg

500     19.1
451     28.0
1713    28.0
171     28.0
3704    28.0
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [123]:
sorted(avg)

[19.1,
 20.0,
 20.9,
 20.9,
 20.9,
 21.0,
 21.0,
 21.1,
 21.2,
 21.3,
 21.3,
 21.3,
 21.3,
 21.3,
 21.4,
 21.4,
 21.4,
 21.4,
 21.4,
 21.4,
 21.5,
 21.5,
 21.5,
 21.5,
 21.5,
 21.5,
 21.5,
 21.5,
 21.5,
 21.5,
 21.6,
 21.6,
 21.6,
 21.6,
 21.6,
 21.6,
 21.6,
 21.6,
 21.6,
 21.6,
 21.6,
 21.7,
 21.7,
 21.7,
 21.7,
 21.7,
 21.7,
 21.7,
 21.7,
 21.8,
 21.8,
 21.8,
 21.8,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 21.9,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.0,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.1,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.2,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.3,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.4,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.5,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.6,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.7,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.8,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 22.9,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.0,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.1,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.2,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 23.3,
 ...]

In [124]:
## Package function --> object.function()
## Built in functionalty --> function(object)

In [125]:
max(avg)

28.9

In [126]:
min(avg)

19.1

## Type conversion in series (Just like Python)

#### I can convert the data type of the given series into another data type.

#### Series --> List ---> list(Series)
#### Series --> Dictionary --> Dict(Series)

In [127]:
avg

500     19.1
451     28.0
1713    28.0
171     28.0
3704    28.0
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [128]:
list_avg = list(avg)

In [129]:
type(list_avg)

list

In [130]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int32

In [131]:
dict_dataframe = dict(dataframe)

In [132]:
type(dict_dataframe)

dict

### Membership operator

## Membership operator --> in --> It checks that whether if a value is in the series or not.
## It checks for the element in the index or label of the series
## We can go with dataframe.values to check that whether if a member is of a series or not.

In [133]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int32

In [134]:
'Amit Singh' in dataframe

False

In [135]:
'Amit Kumar Singh' in dataframe

True

In [136]:
90 in dataframe.values

True

In [137]:
1500 in dataframe.values

False

In [138]:
150 in dataframe.values

True

### Looping in series --> for loop for iterating over the items of the series and for the index iterating we can go with series_name.index

In [139]:
avg

500     19.1
451     28.0
1713    28.0
171     28.0
3704    28.0
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [140]:
for i in avg:
    print(i)

19.1
28.0
28.0
28.0
28.0
20.9
20.9
20.9
21.0
21.1
21.2
21.3
21.3
21.3
21.3
21.3
21.4
21.4
21.4
21.4
21.4
21.4
21.5
21.5
21.5
21.5
21.5
21.5
21.5
21.5
21.5
21.5
21.6
21.6
21.6
21.6
21.6
21.6
21.6
21.6
21.6
21.6
21.6
21.7
21.7
21.7
21.7
21.7
21.7
21.7
21.7
21.8
21.8
21.8
21.8
21.9
21.9
21.9
21.9
21.9
21.9
21.9
21.9
21.9
21.9
21.9
21.9
21.9
21.9
21.9
21.9
21.9
22.0
22.0
22.0
22.0
22.0
22.0
22.0
22.0
22.0
22.0
22.0
22.0
22.0
22.0
22.0
22.0
22.1
22.1
22.1
22.1
22.1
22.1
22.1
22.1
22.1
22.1
22.1
22.1
22.1
22.1
22.1
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.2
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.3
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.4
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.5
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.6
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.7
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.8
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
22.9
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.1
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.2
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.3
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.4
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.5
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.6
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.7
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.8
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
23.9
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.0
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.1
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.2
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.3
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.4
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
21.0
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.5
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
25.0
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6
24.6

In [141]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int32

In [142]:
for i in dataframe.index:
    print(i)

Eric Patel
Cynthia Harrington
Amanda Walker
Jessica Nelson MD
Matthew Sherman
Anna Berry
Richard Arnold
Stephanie Potter
Teresa Aguirre
Anne Adkins
David Clark
Kathleen Weeks
Melissa Kennedy
Kimberly Brown
Jennifer Martinez
Elizabeth Wright
Elijah Ruiz
Thomas Roberts
Julian Gutierrez
Sheila Rivera
Crystal Vargas
Kevin Marquez
Gregory Norman
Jason Hall
Jacob Patterson
Daniel Costa
Vincent Graves
Anthony Huynh
Michelle Rogers
Alison Scott
Sherry Reed
Mr. James Montgomery
Leah Moss
Shelby Pace
Tracie Hogan
Mrs. Katelyn Soto
Monica Henry
Kevin Martinez MD
Kathryn Harris
Allison Phillips
Maxwell Anderson
Terry Meyer
Wanda Hernandez
Brenda Boyd
Anna Frank
Heather Jefferson
Michelle Martinez
Sara Mack
Christopher Taylor
Larry Zimmerman
David Craig
Antonio Reilly
Oscar Gallegos
William White
Brittany Dickerson
Jennifer Kane
Shannon Rodriguez
Sarah Little
Timothy Page
Kim Martinez
Courtney Roberts
Anthony Stewart
Kimberly Mendoza
Ms. Natasha Johnston
Beth Clark
Gina Young
Abigail Herrera
Brittany Ferguson
Tanya Kelley
Stephanie Taylor
Bailey Guerra
Nichole Fleming
Ryan Reynolds
Brandon Hernandez
Stephanie Mahoney
Carlos Mcmahon
Gina Bennett
Latoya Morales
Jennifer Nunez
Whitney Montoya
Michael Summers
Denise Johnson
Vincent Nguyen
John Carpenter
Mia Mccormick
Michael Lee
Mary Evans
Tyler Clark
Frances Brown
Benjamin Green
Dr. Dana Gamble
Mary Johnston
Dillon Casey
Timothy Henson
Timothy Crosby
Philip Ward
Ricky Reed
Ian Heath
Frank Harrington
Christina Tapia
Anita Davis
Marcus Bailey
Jody Espinoza
Amanda Blackwell
Bonnie Arnold
Rebecca Collier
Sharon Johnson
Jessica Gutierrez
Melanie Nelson
Jessica Montoya
Claudia Pace
Renee Evans
Alice Ortiz
Robert Wyatt
David Gilbert
Veronica Diaz
Miguel Smith
Kimberly Rowe
Brent Sanchez
Bryan Carpenter
Wayne Lang
Christopher Logan
Anthony Stewart
Robert Conner
Virginia King
Micheal Morse
Alyssa Waters
Seth Barnes
Elizabeth Allen
Tiffany Jones
Raymond Lambert
Connor Gutierrez
Beth Whitaker
Bobby Hall
Edward Lane
John Hernandez
Dawn Silva
Christopher Cox
Brandon Turner
Brenda Crawford
Matthew Rivera
Janet Hale
Donna Roach
Jacob Ray
Joseph Morton
Travis Wright
Cynthia Brooks
Doris Jones
Christopher Shepard
Candice Howell
Gary Carr
Marie Brewer
Michael Potts
Michael Carroll
Katie Warren
Jason Howard
David Alexander
Stacey Anderson
Danielle Hernandez
Michelle Erickson
Holly Robbins
Travis Powell
April Hawkins
Mrs. Heather Ruiz
Jason Hill
Jesse King
Tiffany Robinson
Rachel Wallace
Edward Oconnor
Daniel Adkins MD
Brian Krueger
Hailey Russell
Michelle Sheppard
Jesse Blair
Jonathan Cox
Sharon Williams
Victoria Frank
Christopher Page
Carlos Garcia
Robert Choi
Gregory Anderson
Tammy Perez
Jennifer Smith
Danielle Johnson
Johnny Moore
Brad Howard
Stephanie Winters
Ryan Howard
Nicholas House
Erin Wilson
Jose Hernandez
Stanley Kennedy
Fred Salas
Scott Guerrero
Lindsay Erickson
Krista Perez
Tami Thompson
Jonathan White
Dana May
Michelle Chambers
Morgan Diaz
Dustin Hutchinson
Aaron Carrillo
Beverly Carpenter
Shelly Garrison
Brett Garcia
Christopher Martinez
Michelle Smith
Karen Brown
Diane Fields
Gregg Chambers
Daniel Nichols
Monica Freeman
Julia Johnson
Tony Brooks
Cody Lee
Amber Beard DDS
Charles Knight
David Watson
Donna Johnson
Yesenia Levy
Pamela Dickson
Jay Villegas
Larry Rodriguez
Kayla Cross
Sheri Spencer
Theresa Harmon
Rhonda Scott
Chelsea Wells
Michael Rodriguez
Shane Cruz
Richard Fisher
Paul Silva
Michael Patrick
Michelle Edwards
Gabriel Romero
Amy Riggs
Frances Willis
Michael Matthews
Jennifer Garcia
Daniel Kramer
Sherry Phillips
Amanda Evans
Thomas Carter
Richard Pineda
James Johnson
Ronald Garcia
Jennifer Mata
Michael Gregory
Maria Cruz
Jason Thomas
Holly Cardenas
Robert Ho
Lisa Olson
Edward Mcknight
Brandy Obrien
Pamela Nunez
Angela Wilson
Mr. Anthony Quinn
Angela Williams
Kayla Hall
Matthew Graham
Elizabeth Thornton
Rachel Fisher
Susan Hoffman
Christopher Weber
Pamela Adams
Angela Walker
Brittany Cruz
Brenda Doyle
David Torres
Austin Pugh
Michael Miranda
Michael Myers
Alan Smith
Brian Gomez
Alfred Olsen
Matthew Clayton
Renee Smith
Adam Barajas
Garrett Trevino
Ryan Durham
Jasmine Nichols
Jacob Snow
Margaret Lee
Jamie Vance
Miguel Pace
Laura Young
Heather Beasley
Mrs. Carrie Delacruz DDS
Brandy Meyer
Donna Carter
Jamie Jones PhD
Christian Mcdonald
Blake Gardner
Shane Hodges
Alisha Roth
Hannah Taylor
Daniel Richardson
Richard Scott
Joshua Allen
Paul Cole
Mrs. Michelle Schmidt DDS
Randy Hernandez
Shannon Johnson
Lisa Barber
Anthony Montgomery
Dylan Johnson
Alex Howard
Bryan Mitchell
Dr. John Briggs
Andrew Cruz
Douglas Wallace
Misty Peterson
Randy Oconnell
Corey Kirk
Hayden Haynes
Taylor Lamb
Stephen Wilson
Miranda Williams
Samantha Krueger
Kimberly Williams
Carol Knox
Mr. Timothy Davis
Jennifer Sharp
Anthony Moreno
Jennifer Simpson
Lauren Rogers
Linda Cole
John Blankenship
Judith Wallace
Carolyn Garcia
Isaac Lopez
Brianna Leach
Michelle Hendrix
Blake Gray
Sarah Brown
Lori Allen
Laura Myers
Michael Allison
Ricky Diaz
Stacey Fleming
Joseph Huffman
Richard Carlson
Charles Collins
Tony Serrano
Toni Wells
Sarah Wilson
Travis Brady
Connie Merritt
Jennifer Blackburn
Taylor Lee
Brianna Serrano
William Carter
Linda Woodard
Benjamin Vargas
Calvin Hernandez
Adam Jones
Faith Gilbert
Caitlin Perkins
Melissa Burton
Michael Sullivan MD
Mr. Thomas Davis
Travis Gallagher
Cindy Clark
Daniel Chang
Thomas Little
William Miller
Sandra Liu
Melissa Cohen
Norman Diaz
Debra Barnett
Alvin Sampson
Megan Schultz
Nicholas Rich
Joshua Howell
Kristine Black
Diane Ramirez
Dennis Hunter
Jason Rodriguez
Joseph Munoz
Jared Avila
James Cruz
Patrick Kennedy
Eric Anderson
Amber Wilson
Gary Johnson
Savannah Phillips
Melissa Salas
Rachel Tate
Jamie Park
Chelsey Hansen
William Jones
Mark Rodgers
William Macias
Vanessa Thompson
Susan Nunez
Charles Briggs
Doris Shaffer
Lori Olson
David Austin
Sheila Williams
Dylan Campbell
Angela Williams
Katherine Williamson
Linda Gill
Michael Castillo
John Jenkins
Megan Jones
Tina Hernandez
Mrs. Melissa Dawson
Richard Arnold
Cameron Baker
Elizabeth Barnes
Stephen Taylor
Jordan Houston
Victor Williams
Michelle Hines
Amy Stuart
Jasmine Garcia
Larry Hernandez
Amy Rivera
Debra Wyatt
Jennifer Hines
Christine Mccarthy
Mark Jacobs
Daniel Trujillo
Lauren Sullivan
James Kaufman
David Williams
Jennifer Brown
Brandon Keller
Melanie Davis
Steven Carson
Joshua Atkins
Heidi Diaz
Laura Hughes
Derek Savage
Debra Mendoza
Brian Luna
Benjamin Mann
Jeremy Sullivan
Rebecca Johnson
Angela Holmes
Elizabeth Mcconnell
William Robbins
Seth Smith
Kirk Miller DVM
Stephanie Wood
Johnathan Walsh
Patricia Holloway
Jeanette Carlson
Jennifer Smith
April Potter
Joanna Boyd
Jose Watson
Curtis Francis
Connie George
Mary Rose
Jennifer Morgan
Mrs. Maureen Lee DVM
Rachael Rodriguez
Christopher Ward
Jasmine Ramirez
Charles Clark
Benjamin Harris
Raymond King
Mary Leach
David Bauer
Janet Martinez
Sheila Harris
Mark Sullivan
Kevin Hill
Amanda Frazier
Dean Schneider
Matthew Taylor
Courtney Stewart
Robert Parks
Julie Joseph
James Jackson
Daniel Simpson
Andrew Newman
Joseph Bates
Lisa Vega
Jill Oneal
Kevin Richardson
Patrick Gardner
Jonathan Williams
Matthew Mitchell
Jennifer Kelly
Steven Conrad
Adam Duran
Amy Russo
James Anderson
Dr. David Brooks
Ryan Stephens
Jessica Davidson
Andrew Parker
Brittney Parker
George Hurst
Brittany Gross
Nichole Greer
Jonathan Hess
Zoe Peterson
Tina Hernandez
Melissa Clayton
Rachel Richardson
Jennifer Norris
Susan Fitzpatrick
Richard Jones
John Cooke
John Luna
Ashley Daniels
Douglas Miller
Jeffrey Li
Briana Rodriguez
Jay Johnson
Tyler Grant
John Turner
Kristin Nichols
Robert Diaz
Brandon Stark
Meghan Chambers
Jacqueline Crawford MD
Duane Roberts
Rachael Newman
Matthew Wright
Jason Duncan
Anthony Garcia
Jennifer Stevens
Cameron Spencer
Lisa Chan
Kimberly Miller
Dustin Nelson
Marissa Price
Jennifer Flores
Tiffany Hutchinson
Kristen Ross
Diane Stout
Marcia Harrison
Linda Smith
Erika Skinner
Steven Montoya
Jennifer Barrett
Katrina Howell
Kevin French
Deborah Ray
Michael House
Hannah Gardner
Colleen Lane
Brent Myers
Yvonne Rodriguez
Sarah Johnson
Paul Barnes
Russell Kelly
Catherine Newton
Amy Lee
Sarah Smith
Mr. Dylan Welch
Justin Jenkins
Elizabeth Mills
Dr. Mary Gonzalez
Christina Trevino
Christy Hernandez
William Fischer
Elizabeth Smith
Kyle Higgins
Wayne Jensen
Deanna Oconnell
Thomas Buckley
Vincent Hendricks
George White
James Carroll
Phillip Thompson
Laura Grimes
Paul Cain
Brian Avila
Sandra Perez
Thomas Brown
Diana Cook
Kimberly Santana
Joseph Kaufman
James Waller
Monica Sanchez
Stephanie Cross
Briana Bird
Mrs. Martha Moore
David Hoffman
Jennifer Molina
Emily Brown
Eric Chung
Tina Atkinson
Catherine Clark
Barbara Hall
Rebecca Perry
Angela Mathis
Kevin Jones
Heather Conway
Tiffany Ward
Allison Dougherty
Scott Jones MD
Brandon Stewart
Brett Howard
Karen Lee
William Kim
Corey Stevens
Molly Brady
Tara Walker
Sarah Nguyen
Michelle Morris
Mary Salinas
Paul Craig DDS
Anita Meza
Jacob Wilson
Christine Ho
Maria Martinez
Wendy Brewer
Jaime Castro
Ronald Hayden
Jessica Garza
Christopher Mccormick
Steven Williamson
Katherine Miles
Christopher Rodriguez
Patrick Campos
Michael Gill
Diana Johnson
Michael Wells
Ashley Schultz
Frank Chung
Heather Cameron
Angela Friedman
Kylie Woodward
Anthony Hernandez
Sheila Morrow
Miranda Kramer
David Santiago
Mary Black
Pamela Aguilar
Amy Patel
John Marquez
Ashley Rodriguez
Joshua Goodman
Tammy Bowman
Billy Alvarado
Charles Levy
Adrian Smith
Brian Nelson
Carolyn Moran
Jennifer Gallegos
Carol Berry
Patricia Frank
Audrey Leblanc
Anthony Harrison
Lauren Martinez
Michael Montgomery
Mark Bush
Tonya Duncan
Joanne Pollard
Gregory Pierce
James Rose
Wesley Wood
Christina Cox
George Smith
Christian Esparza
Alexander Blackwell
Ivan Bernard
Jeff Lozano
Sarah Kirby
Tiffany Lin
Adrian Sullivan
Makayla Gray
Alisha Adams
Antonio Green
Mark Gill
Christina Smith
Kenneth Lamb
Cynthia Todd
Jason Riggs
Julian Hays
John Galloway
Ryan Johnson
Brittney Garner
Carla Smith
Michelle Mccormick
Patricia Diaz
Thomas Johnson
Jason Swanson
Alexander White
Casey Bowen
James Smith
Melanie Wright
Tina Lopez
Nicole Smith
Roger Atkinson
Anna Nichols
Joshua Coleman
Carol Walker
Joseph Esparza
Jordan Davis
Kimberly Bright
Robin Stanley
Rhonda Fields
Sarah Young
Stephanie Wallace
Deborah Taylor
Leah Stewart
Jared Hayden
Linda Cardenas
Valerie Whitaker
Heather Morales
Claire Murillo
Lori Barron
Steven Arellano
Theodore Owens
Mary Davis
Charles Norris
Sean Hall
John Castro
Christopher Park
Joseph Torres
Michael Smith
Michael Miller
Amanda Baker
Theresa Smith
Barry Flores
Stephen Taylor
Destiny Rivera
Julie Chan
James Hicks
Belinda Mason
Hayley Martinez
Jerry Kirby
Joseph Wilson
Tiffany Hart
Nancy Hartman
Gabrielle Gardner
John Gonzalez
Michael Johnson
Selena Baker
Jimmy Diaz
Dr. Sarah Miranda
Benjamin Craig
Nicole Thomas
Michelle Turner
Alan Barnes
James Vaughn
Kylie Baldwin
Jason Larson
Eric Jackson
Joseph Mclean
Eric Bailey
Jennifer Bruce
Mr. Michael Snyder
Samuel Friedman
Elizabeth Sherman
Erin Gray
Brian Thomas
Joshua Diaz
Adrian Robles
Dominique Hughes
Stephanie Guerra
Kirsten Jackson
Michael Hawkins
Brandon Goodman
Catherine Hardin
Jeremiah Freeman
Theresa Smith
Victor Green
Dillon Bond
Patricia Harrison
Jacob Newman
Matthew Pugh
Caroline Roberts
John Johnson
Roy Browning
Aaron Rogers
Cheryl Pierce
Michael Snyder
Crystal Gallagher
Janice Patel
Patricia Martinez
Carlos Castillo
Lori Cisneros
Ricardo Gamble
Cynthia Jennings
Randall Henry
Anne Porter
Ashley Underwood
Susan Dominguez
Robin Williams
Makayla Smith
Brooke Silva
Theresa Carter
Lisa Hartman
Megan Mcgee
Victoria Garrett
Patricia Smith
Connie Peterson
Julia Bridges
David Baker
Earl Rivera
Stacey Martin
Maria Mitchell
Raymond Anderson
Nicole Matthews
Michael Hall
David Horton
Jeffrey Patterson
Robert Powell
Gina Haley
Amber Woods
Sarah Mcmahon
Mary Thompson
James Brown
Bradley Williams
Nicholas Evans
Kelly Beasley
Michael Garrison
Janet Johnson
Mark Henderson
Tyler Hernandez
Jason Rodriguez
Christopher Roberts
Cory Grant
Anita Ruiz
Dylan Perez
Sierra Navarro
Daniel Wells
Bryan Perez
Anthony Dennis
Edward Moreno
Sabrina Murphy
Anna Smith
Jasmine Smith
Joseph Ryan
Brianna Simmons
Jason Gray
Casey Porter
Adrian Schroeder
Eric Odom
Joshua Dean
Steven Mueller
John Jones
Jose Rosales
Billy Wells
David Smith
Nicholas Welch
Jimmy Scott
Julie Gibson
Daniel Jarvis
George Schultz
Heidi Wright
Charles Owens
Drew Gay
Christopher Mitchell
James Brooks
Caleb Sanchez
Adam Hernandez
Melissa Johnson
Deanna Smith
Charles Brooks
James Cooper
Michael Williams
Laura Hoffman
Dawn Kane
Brady Terry
Matthew Lester
Melvin King
Chelsea Bates
Stacy English
Ricky Rodriguez
Jessica Morris
Cindy Jenkins
Amber Morton
Joan Suarez
Heather Schroeder
Shelly Miller
Michael Liu
Nicolas Russo
Richard Atkins
Theresa Mendoza
Crystal Gonzalez
Jared Ray
Peter Wang
Christina Cole
Carla Nelson
Heidi Lopez
James Hooper
Andrea Long
Natalie Pierce
Donna Jackson
Felicia Henry
David Bullock
Michael Cunningham
Dr. Laura Buchanan
Teresa Ford
John Parker
Stephen Navarro
Tabitha Martinez
Andrew Lawson
Anthony Cox
Charles Lee
Jerry Baker
Michael Duncan
Corey Stephenson
Katrina White
Joshua Patel
Kimberly Gordon
Misty Wong
Randall Hoffman
Michelle Sanchez MD
Andrew Short
Marie Baker
Adrian King
Collin Schultz
Vanessa Rodriguez
Melissa Hernandez
Kathryn Parker
Amanda Drake
Joseph Alvarez
Craig Blair
Susan Harris
Anna Jarvis
Mary Lopez
Michael Barrett
Kristin Davis
Julie Moran
Mark Vaughn
Lisa Woods
Zachary Russell
Dr. Michael Hayes
Lisa James
Mrs. Eileen Lee MD
David Simpson
Lindsay Wells
Larry Valdez
Michael Smith
Melanie Rangel
Travis Perez
Clayton Williams
Norma Diaz
Wesley Tucker
Amanda Manning
Mark Wallace
Elizabeth Costa
Patricia Haynes
Christopher Wang
Leonard Sandoval
Sandra Scott
Christopher Lee
Peter Tran
Derek Harmon Jr.
Patty Kim
Denise Weiss
Charles Martinez
Timothy Smith
Jesus Flynn
Jamie Everett
Joseph Dalton
Courtney Johnson
David Rodriguez
Patrick Miller
Erika Kent
Monica Green
Lisa Williamson
Ethan Ritter
Vincent Hogan
Michelle Green
Holly Rich
Brittany Schmidt
Christopher Marshall
Gary Moreno
Patrick Nolan
Jeremy Jimenez
Susan Mills
Chad Small
Jennifer Reese
Steven Moore
Angela Pacheco
Amy Garcia
Alex Mann
Paul Waters
Mr. Brendan Porter
Colton Brewer
Debbie Robinson
Rachel Choi
Tammy Tucker
Phillip Willis
Neil Drake
Johnny Green
Wendy Mathews
Matthew Booker
Roy Watson
Molly Clark
Anthony Howe
Robert Hess
Ann Ward
Amanda Bauer
Ronnie Crane
Christopher Parker
Kristen Shaw
Jenna Ewing
Samuel Brown
Martin Taylor
Laura Smith
Elizabeth Moore
Peter Bowen
Gary Young
Roberto Huynh
Erika Russell
Donald Duran
Joshua Harvey
Thomas Browning
Shannon Thompson
Sean Austin
John Williams MD
Norman Frazier
Eric Morgan
Gina Perez
Mark White
David Cummings
Wyatt Benjamin
Cody Adams
Zachary Brown
Connie Miranda
Mary Welch
Anthony Martin
Nancy Smith
Angel Harrison
Morgan Juarez
Michael Hunter
Christopher Walter
Andrea Gibbs
Michele Cuevas
Nathan Wilson
Aaron Burns
Paul Hull
Jacob Rocha
Janice Moss
Steven Townsend
Richard James
Sara Nelson
Cathy Castro
Thomas Brown
Sherri Bowen
Katelyn Peters
Erin Glenn
Tony Johnson II
Philip Bell
Nicholas Hubbard
Olivia Morris
Richard Hunt
Karen Smith
Spencer Rodriguez
Jeffery Walls
Christian Warner
Trevor Mccarthy
Holly Smith
Ashley Hanson
Craig Morris
Philip Harrison
Sara Graham
Julia Hall
Anita Davis
Kevin Williams
George Brown
Anna Adams
John Fowler
James Martin
Alejandro Wilson
Lee Harris
Glenn Cunningham
James Dixon
Richard Ray
Erin Mcconnell
Alan Gonzalez
Cindy Strong
Benjamin Prince
Mr. Gregory Joseph
Lisa Moore
Daniel Simmons
Robert Peterson
Amanda Cox
Steven Conrad
Benjamin Murray
Natalie Gonzalez
Daniel Smith
Mr. Joseph Schultz
Yvonne Jones
Morgan Ball
Brianna Riley
Dr. Jonathan Price
Alexander Medina
Troy Brown
Daisy Gillespie
Benjamin Wilson
Tasha Smith
Chris Wilson
Janice Glover
Robert Jones
John Collins
Philip Adkins
Dennis Marshall
Stacy Gutierrez
James Riley
Joe Blackwell
Alexander Smith
Amanda Jackson
Thomas Haley
Adrian Winters
Kathleen Warren
Vincent Vazquez
Garrett Collins DDS
Richard Schwartz
Brian Wilson
Kyle Vargas
Aaron Smith
Mark Levine
Kathryn Robertson
Christine Parker
Kyle Berg
Kelly Jones
Ryan Cobb
James Kim
Eric Clark
Jeffrey Duarte
John Short
Amanda Frazier
David Perez
David Doyle
Kevin Marshall
James Boyd
Laura Perez
Richard Marshall
Mr. Ronald Guerrero
Anna Morton MD
Tiffany Landry
Paul Farrell
Jeremy Johnson
Michelle Callahan
Wendy Gibson
Jessica Wright
Casey Charles
Kristina Sweeney
Thomas Phillips
Kimberly Little
Jessica Graham PhD
Allen Martinez
Anthony Maldonado
Casey Mccall
Lauren Davis
Robert Knapp MD
Mitchell Gentry
Chad Dixon
Tracey Martinez
Ronald James
Sarah Allen
Nicole Juarez
Nicole Guerra
David Quinn
Patricia Maynard
Sean Henson
Julie Thompson
Corey French
Cassandra Pruitt
Virginia Williams
Kevin Moreno MD
Andrea Villegas
Ryan Alexander
Shawn Patrick
Jessica Beck
Mrs. Melissa Zimmerman
Edward Stevens
David Norman
Bradley Nichols
Maria Sullivan
Teresa Smith
Denise Garcia
Mr. Joshua King
Mr. Alexander Gonzalez
Lisa West
James Adams
Melinda Wilson
Tracy Johnson
Glenn Gutierrez
Nicole Smith DVM
Maria Hill
Haley Barnes
Cindy Carroll
Nathaniel Osborne
Melissa Owens
Matthew Barajas
Ricky Robinson
Kristina Wright
Lauren Perez
Jaime York
James Summers
Jennifer Smith
Ronald Scott
Daniel Douglas
Alexis Perkins
Bailey Hunt
Tina Rivera
Jose Brown
Kimberly Myers
Joshua Barron
Sarah Jones
Yvonne Morales
Emma Conrad
Michelle Butler
Daniel Gibson
Katherine Woodward
Nichole Schultz
Amy Osborn
Dr. Justin Morris
Joseph Lopez
Thomas Gonzalez
Monique Howe
Steven Hill
Curtis Trevino
Gary Wallace
Wayne Rose
Hayden Bond II
Willie Klein
Eric Alvarez
Donna Conley
Jean Murphy
Felicia Simmons
Tracy Hanson
John Payne
Jason Brown
Randall Smith
Patrick Mendez
Susan Silva
George Reed
Robert Chang
Tracey Jacobs DVM
Christina Rubio
Brittney Ponce
Matthew Webb
Thomas Harmon
Meredith Clark
Mr. Steven Mckee
Margaret Davis
Melissa Green
Alicia Smith
Jessica Miller
Ellen Walters
Edward Obrien
Melissa Hansen
Kenneth Orozco
Ashley Ramsey
Rodney Edwards
Morgan Glover
Jennifer Garcia
Ryan Phillips
Stephen Ortiz
Wendy Maxwell
Michael Baker
Timothy Phillips
Lisa Chang
Joshua Peterson
Debbie Reynolds
Sylvia Lopez
Antonio Jones
Jason Turner
Steven Steele
Heather Bishop
Shane Wilson
James Perkins
Brett Robinson
Peter Cain
Dawn Pierce
Jennifer Smith
Robert Griffin
Marcus Nielsen
Tonya Baldwin
Dennis Griffin
Yolanda Robinson
Johnny Rivera
Kristina Harris
Wendy Levine
William Stanley
Scott Ramirez
Melissa Clark
Madison Lamb
Derrick Harper
William Hernandez
Ana Newton
Jasmin Atkinson
Joseph Mendoza
Stanley Strickland
Jason Phillips
Raymond Deleon
Matthew Lara
Andrea Webb
Karen Rowe
Joseph Norman
Rebecca Bennett
Hannah Moore
Nathaniel Brown
Lisa Pineda
Robert Cooper
Rachel Jones
Lisa Griffin
Brett Murray
William Rodriguez
Andrew Medina
Aaron Contreras
Donna Thomas
Kelly Malone
David Mosley
Chad Montgomery
Patricia Hall
Joseph Powell
Emily Combs
Scott Jones
Aaron Robinson MD
Valerie Diaz
Crystal Harris
Christina Johnson
Devin Stevens
Kevin Bennett
Angela Alexander
Carol Jimenez
John Wilson
Mr. Jamie Cruz
Christina Davis
David James
Lauren Hernandez
Daniel Hurst
Daniel Middleton
Brent Taylor
Paul Jimenez
Brian Chapman
Sarah Hicks
Brandon Chaney
Cassandra Carter
Jason Bailey
Veronica Allen
Brandi Smith
Megan Montoya
Cole Harris
Raymond Baker
Leah Thomas
Rachel Espinoza
Gloria Johns
Joshua Anderson
Jesse White
Christine Taylor
Paul Alvarado
Bethany Wallace
Sean Mann
Rachael Maxwell
Patrick Wilkinson
Michael Murray
Kelly Vargas
Sherry Ali
William Williams
Chad Cameron
Scott Evans
Nancy Crane
Shannon Allen
Steve Brown
Christina Webster
Austin Thomas
Mark Gardner
David Tran DVM
Jason Hess
Beth Garrison
Jessica Carter
Stephen Richardson
Eric Frazier
Erika Lee
Stephanie Martin
Joseph Cisneros
Carlos Barnes
Nicole Harrell
James Miller
Debra Williams
Taylor Pacheco
Michael Perez
Robert Hunter
Robert Moreno
Christopher Robinson
Sharon Patrick
Cassidy Morton
Grant Hall
Stacy Diaz
Kathleen Bailey
James Douglas
Aaron Melendez Jr.
Willie Wilkerson
Greg Stewart
Christy Mitchell
Jessica Cruz
Mary Hernandez

In [143]:
for i in dataframe.values:
    print(i)

68
75
282
302
129
98
494
133
316
140
52
149
53
299
383
79
373
59
500
332
133
228
445
477
405
423
279
428
269
160
302
484
420
148
460
271
51
208
398
115
343
97
153
406
260
346
133
241
150
56
114
73
246
476
487
327
469
78
468
405
269
124
107
356
412
69
96
205
161
399
255
235
172
416
123
265
377
497
228
388
405
210
463
256
215
163
190
280
492
340
189
101
290
120
53
138
467
145
105
456
258
59
442
136
252
258
402
247
273
198
158
150
116
273
161
391
191
482
308
426
190
124
247
366
345
390
467
140
338
287
91
386
458
330
160
469
424
496
432
356
89
309
152
414
485
304
66
318
99
183
230
308
185
127
414
154
233
191
190
405
57
66
158
328
451
287
346
152
313
276
253
65
268
392
416
308
287
485
174
131
80
111
136
421
93
126
480
475
492
117
429
487
339
158
464
306
93
218
375
93
302
115
210
94
135
176
372
272
443
426
95
351
159
285
378
441
259
223
325
399
469
467
443
142
337
388
93
174
441
430
234
489
500
367
365
56
129
173
60
92
60
202
341
378
282
197
182
217
63
309
379
253
134
439
122
154
323
472
368
362
373
297
165
58
189
403
461
137
105
388
71
376
358
339
207
350
436
186
96
435
89
175
427
349
352
55
470
109
190
236
281
85
469
77
421
197
130
259
129
345
168
101
334
227
145
170
100
453
148
475
483
334
108
473
420
349
210
127
395
97
426
340
482
442
116
97
388
451
459
281
97
310
311
243
374
60
266
396
227
255
328
315
129
306
251
147
349
135
411
238
146
455
449
233
362
357
167
365
467
203
273
66
52
111
70
311
56
417
119
465
341
96
449
256
85
355
343
278
469
400
451
413
223
230
446
494
274
74
70
179
354
378
500
141
427
423
79
207
442
230
441
179
102
395
370
74
479
318
404
170
198
152
334
160
422
155
485
73
150
233
448
439
481
380
235
430
420
185
111
188
167
292
145
379
235
301
463
85
417
187
400
64
62
327
74
266
215
279
461
175
392
64
133
54
128
471
286
103
127
64
185
371
390
442
252
371
93
257
96
305
183
227
484
84
216
326
255
122
270
488
494
219
256
194
162
116
402
228
468
75
281
105
500
293
236
235
59
289
416
302
50
143
454
78
474
274
204
325
391
476
154
108
370
84
214
454
50
58
200
60
410
432
375
155
221
426
125
346
64
54
340
113
138
54
115
352
275
411
262
105
337
116
128
371
387
274
423
402
395
345
61
190
112
466
131
372
123
196
340
215
219
102
202
50
331
216
74
130
174
225
245
183
456
448
480
282
147
489
456
226
283
413
294
483
419
351
207
117
427
387
362
499
481
491
366
134
246
174
429
50
158
399
345
347
323
233
88
284
172
51
443
480
368
107
394
289
298
323
413
444
194
140
454
328
75
265
216
356
221
453
439
335
64
466
124
429
500
438
204
410
320
324
63
379
118
371
449
247
375
76
435
138
439
496
354
245
232
488
332
60
448
428
146
116
436
370
209
108
331
198
135
365
177
259
492
186
394
294
155
257
184
197
50
380
432
229
331
275
347
156
159
178
152
133
487
187
185
341
307
107
230
424
182
236
434
332
234
211
344
106
251
461
382
387
429
401
488
67
248
158
213
448
309
268
162
186
90
139
376
291
311
447
258
420
67
200
435
129
460
389
128
480
206
483
477
73
499
367
194
127
491
181
429
375
481
71
133
494
408
202
296
366
353
347
294
57
500
214
249
114
259
456
285
275
473
482
125
451
456
57
397
484
426
349
88
262
202
95
223
66
166
69
206
360
396
237
367
400
117
89
211
410
169
496
480
496
78
112
205
97
249
93
206
441
279
445
253
425
311
141
56
206
187
359
400
222
92
321
362
493
216
78
189
139
244
444
328
254
235
94
219
481
119
90
131
317
274
312
148
307
414
300
284
343
115
52
485
274
181
363
255
366
159
335
399
371
63
65
90
89
305
274
287
177
285
243
253
210
63
347
217
357
468
211
287
146
480
266
76
235
369
76
440
359
422
212
71
492
463
171
230
454
169
366
449
443
100
184
98
150
211
170
370
207
247
405
158
480
93
245
459
265
407
324
114
62
498
239
470
284
81
473
248
458
93
105
319
224
436
253
264
78
473
315
381
434
328
171
471
451
125
100
121
171
398
118
325
153
409
344
486
303
242
200
449
159
131
478
290
117
354
120
155
466
381
389
201
178
447
53
481
141
86
125
136
396
114
307
481
351
335
467
361
483
437
195
421
267
292
280
398
301
238
453
323
292
145
342
404
99
340
295
191
448
98
265
77
405
121
65
362
372
412
76
427
211
79
408
264
327
277
413
490
351
134
57
314
352
383
407
211
228
302
373
194
175
230
387
168
129
395
288
84
328
426
240
400
165
262
292
70
353
332
457
436
176
492
78
362
192
343
319
183
466
127
440
314
159
438
297
73
257
85
63
426
142
190
78
445
64
111
422
290
72
285
97
81
144
166
146
108
222
500
236
346
397
211
349
122
258
81
177
139
228
474
77
127
112
410
390
393
405
118
250
311
323
201
456
200
363
397
81
408
66
433
430
98
85
218
155
199
491
481
475
315
177
64
300
304
216
118
139
189
53
361
473
154
455
418
392
132
435
147
67
256
131
123
242
280
149
295
214
175
454
357
132
121
413
89
303
473
472
146
249
326
489
118
364
326
483
450
280
389
129
200
82
449
362
273
391
208
274
234
123
245
485
229
433
239
413
405
116
323
367
370
99
73
386
156
118
335
321
245
447
359
305
437
80
434
344
414
196
441
299
461
469
253
461
83
395
90
459
449
311
175
481
114
148
428
287
416
348
449
471
222
361
169
270
161
354
436
436
98
233
86
381
237
55
97
460
297
145
237
245
119
391
106
185
156
461
126
126
288
124
91
207
403
232
468
66
347
260
414
52
66
223
136
62
497
116
205
158
319
303
239
194
202
373
159
312
380
428
469
382
365
371
388
118
481
257
340
395
226
424
359
246
62
300
464
475
311
110
483
380
421
51
91
491
376
206
331
296
148
63
239
109
467
182
454
371
246
160
368
129
139
51
257
215
400
441
458
244
436
273
439
432
129
70
401
276
375
230
136
295
224
300
436
372
351
482
167
211
83
53
409
378
235
371
384
118
212
412
469
105
314
382
365
339
489
309
388
160
81
376
75
444
225
166
93
269
279
369
381
67
228
474
307
395
398
143
249
268
413
294
296
164
440
67
284
106
451
344
444
140
298
64
67
122
72
460
257
264
114
259
253
433
71
442
463
362
321
195
442
415
260
320
215
334
100
298
346
74
120
384
337
107
340
84
434
467
258
450
455
114
320
145
282
316
286
254
245
258
65
173
134
377
91
199
322
170
417
182
388
210
57
303
316
137
138
399
109
267
217
129
439
78
153
400
169
85
319
93
172
496
333
90
296
355
142
206
171
475
73
396
213
323
163
182
69
459
380
258
369
161
208
475
474
171
157
457
302
261
369
389
281
373
440
103
298
342
140
125
203
494
468
174
458
207
247
246
331
198
97
59
215
266
126
409
424
487
293
58
64
241
481
54
240
472
360
416
194
179
345
385
188
357
174
366
329
96
432
436
295
284
422
154
106
401
296
307
174
389
481
379
215
76
251
366
143
95
165
423
406
112
153
357
424
454
429
417
165
134
398
264
410
269
188
405
499
496
65
210
50
214
214
165
183
297
288
257
448
132
443
142
90
339
429
348
378
67
422
343
423
268
152
224
125
259
306
52
124
265
232
341
86
352
473
359
437
127
79
200
364
290
224
133
72
376
315
327
265
269
159
242
489
453
323
361
296
74
151
285
217
277
401
97
344
115
370
320
320
354
102
110
365
151
255
390
68
389
191
479
463
65
496
390
262
329
250
211
351
300
444
104
423
417
420
408
316
294
496
278
420
64
111
171
254
356
198
115
55
240
461
51
301
60
290
247
141
475
399
488
353
248
416
133
72
496
395
100
170
120
222
202
438
257
436
263
343
348
227
75
51
72
193
156
104
433
361
390
275
78
66
165
461
173
339
199
315
467
182
104
152
140
99
59
262
304
69
131
348
442
227
254
299
460
291
56
125
255
96
291
88
298
192
208
54
110
81
455
189
176
224
347
369
478
95
295
252
415
490
429
446
153
473
170
338
77
220
490
197
332
106
271
400
228
287
105
278
311
60
495
275
432
120
482
127
230
327
261
430
144
389
326
342
371
309
431
382
104
324
299
300
465
311
313
149
175
440
300
465
432
128
187
77
344
441
266
255
206
126
324
371
53
236
349
122
245
430
166
275
210
440
340
97
232
256
61
440
399
125
329
229
462
360
171
64
166
482
229
498
357
144
455
418
62
373
148
86
419
102
314
140
487
51
71
328
91
231
252
170
181
269
345
253
478
500
240
56
374
270
134
229
229
468
429
476
256
424
367
198
339
303
475
372
301
305
401
255
432
347
215
340
451
368
408
428
84
94
88
159
143
144
476
313
303
482
172
134
262
499
469
121
126
149
461
346
183
224
353
195
243
261
323
96
159
191
362
244
429
54
463
297
382
439
180
240
381
411
153
320
359
130
226
375
116
137
207
172
88
425
112
68
484
404
153
275
259
396
114
402
407
487
359
145
89
221
349
320
418
437
462
310
55
128
262
298
324
245
327
162
303
471
91
186
111
99
402
288
239
376
199
228
315
91
240
456
119
237
408
491
496
336
246
294
485
207
302
111
312
317
285
129
205
71
499
335
241
249
176
205
68
289
217
332
331
360
347
489
270
237
281
384
255
357
345
466
293
328
304
182
162
480
362
270
180
408
83
490
431
219
82
74
214
231
108
246
282
255
176
54
481
182
409
189
292
456
442
112
457
339
224
86
324
399
180
120
172
421
123
97
412
215
415
101
480
271
489
467
472
430
365
94
205
104
288
323
173
165
243
142
101
497
198
467
98
257
469
415
462
236
330
352
434
145
151
111
491
52
380
187
236
177
308
451
310
209
60
307
257
198
347
75
405
397
296
371
369
208
105
359
229
319
374
188
134
197
226
317
94
264
202
285
438
390
201
224
208
476
442
161
466
271
423
416
158
111
237
225
59
362
76
166
174
403
289
152
352
494
492
96
267
219
360
113
68
242
150
137
455
235
130
282
469
404
362
131
344
281
219
92
484
258
369
71
429
399
445
84
227
68
496
489
433
208
74
457
356
463
57
88
191
426
108
321
391
96
224
435
52
367
75
481
285
326
243
412
451
241
129
326
246
474
74
113
153
129
81
292
287
294
125
399
203
370
349
71
284
325
316
61
314
332
84
397
235
71
277
341
204
470
67
306
94
194
175
235
277
327
218
393
109
140
280
332
443
104
81
225
121
485
215
356
490
339
234
184
375
120
361
492
266
152
343
298
56
180
388
457
366
495
408
277
174
223
417
397
256
478
466
230
108
464
97
207
209
122
229
307
124
470
285
127
409
424
164
133
54
169
380
402
312
141
443
135
336
228
223
446
145
428
460
463
479
434
450
168
253
65
278
172
233
437
479
224
164
463
117
297
86
350
253
150
123
76
423
185
173
122
479
305
232
265
446
323
242
197
405
307
203
59
228
76
189
208
366
154
109
441
267
445
85
266
347
387
274
475
142
104
391
156
424
69
342
81
260
58
251
55
273
360
347
468
84
287
462
462
249
372
226
211
54
306
81
196
220
227
109
211
499
136
143
143
248
288
491
465
275
220
107
381
169
172
438
418
420
351
415
248
380
160
475
209
297
205
382
156
104
337
490
277
114
327
258
218
75
100
293
221
399
362
466
369
352
463
260
158
249
252
438
401
233
437
212
324
475
403
196
485
62
444
135
327
61
335
304
352
179
416
326
127
350
185
373
200
196
191
387
176
341
107
217
328
82
494
88
126
370
349
216
71
487
400
222
219
282
340
375
471
130
479
87
327
231
351
357
56
119
122
81
163
107
334
120
321
93
447
253
100
160
132
290
328
245
491
227
272
469
372
177
486
248
337
91
191
263
411
295
112
353
218
498
123
396
457
108
282
293
83
254
289
185
97
392
162
310
320
305
177
204
65
331
78
413
85
296
361
161
257
362
377
409
324
95
384
112
284
312
54
135
376
238
288
154
383
136
148
302
307
495
117
330
198
388
50
340
51
322
129
132
107
254
237
344
178
187
346
471
209
286
389
397
377
481
426
318
401
390
125
51
72
103
172
415
412
415
259
118
61
99
355
460
115
412
120
124
191
96
310
390
109
286
486
114
116
56
243
93
275
374
450
285
221
91
111
359
198
240
219
303
321
243
297
53
415
62
438
451
235
437
289
91
113
478
193
383
393
414
178
161
467
258
386
136
263
344
465
133
408
85
407
227
498
224
320
395
431
82
306
65
127
84
280
275
116
213
425
192
85
290
212
331
119
166
340
307
217
228
182
314
241
73
479
418
329
407
488
385
449
317
208
485
316
211
141
265
76
152
443
72
255
308
483
147
392
442
178
225
349
253
454
429
492
439
66
103
409
389
114
86
246
398
58
206
92
428
376
79
261
340
302
293
467
409
226
338
186
212
334
90
340
452
177
429
193
375
208
253
115
57
441
427
471
291
137
347
351
220
355
441
337
480
398
356
380
344
378
146
56
342
271
423
364
470
98
330
98
362
253
406
356
484
433
162
75
206
432
165
371
392
133
258
169
67
281
316
317
204
474
135
349
349
114
317
171
154
409
157
189
484
103
55
163
331
486
62
481
289
236
327
225
403
184
69
247
365
184
55
183
499
452
493
370
395
303
52
165
291
233
426
80
301
273
449
433
257
98
342
179
349
313
124
372
288
493
279
434
312
294
407
121
162
229
348
328
123
52
239
331
278
492
113
263
307
339
363
150
330
64
141
470
76
483
229
131
222
58
266
432
275
296
273
432
244
240
305
172
202
253
157
126
294
482
270
489
409
498
271
433
206
73
165
341
67
284
452
152
120
152
465
172
114
470
449
346
413
166
490
78
296
240
443
276
398
169
243
400
416
343
416
410
285
483
365
211
86
309
381
354
146
212
189
331
398
144
472
259
59
426
53
106
91
72
200
193
95
60
215
107
158
432
479
197
179
160
360
94
380
54
280
140
92
368
412
208
389
183
398
160
364
472
486
460
179
317
83
119
312
309
393
260
276
458
249
120
283
476
297
141
450
227
400
312
298
309
492
132
356
251
442
249
362
484
464
429
362
72
469
103
126
186
303
409
113
309
175
142
156
424
309
266
391
348
250
382
84
164
67
252
73
366
81
466
113
380
392
476
449
63
102
180
166
100
84
333
171
112
352
233
51
248
133
197
129
323
496
365
123
419
417
191
393
230
234
297
152
325
88
236
156
297
263
448
300
411
409
60
175
226
199
383
418
180
462
234
50
372
87
480
260
205
412
64
119
387
388
468
86
242
66
497
465
199
374
413
135
178
135
302
420
53
241
473
490
389
394
435
176
102
172
398
216
312
461
369
321
421
319
105
75
225
380
183
82
292
402
76
290
433
295
83
269
141
167
54
488
470
310
474
390
391
427
88
327
130
304
471
90
248
216
275
471
343
312
132
467
365
165
174
312
438
127
354
411
431
431
250
252
246
95
274
423
431
404
412
353
294
493
88
248
452
305
343
377
154
63
268
472
173
348
305
88
53
438
302
334
427
400
478
205
462
438
410
476
422
224
481
142
50
278
461
126
413
392
81
93
317
200
114
499
481
484
171
253
338
333
71
424
287
361
184
489
61
154
471
444
455
175
155
276
343
438
460
487
332
136
459
313
418
208
219
357
172
371
217
252
214
494
253
154
104
317
86
316
360
379
112
192
385
113
157
58
198
255
180
408
301
191
442
154
151
397
476
479
345
117
483
225
270
222
254
448
318
179
83
333
87
202
398
128
92
116
180
343
457
470
403
277
141
134
262
483
240
488
399
267
365
460
96
363
70
191
304
170
359
168
236
157
118
381
396
458
72
109
113
74
375
345
179
464
60
161
156
461
151
363
308
215
364
456
150
120
211
154
297
475
249
473
184
469
485
471
139
266
440
384
68
170
492
329
498
216
250
179
480
160
312
297
232
190
373
159
154
448
247
327
385
460
209
442
443
417
257
326
234
159
272
160
287
357
267
383
327
68
114
353
50
378
214
108
268
493
100
437
387
170
94
303
320
390
205
221
168
104
288
90
166
182
488
170
226
99
415
347
470
266
69
64
181
377
242
339
398
358
230
201
493
373
414
149
191
347
232
282
146
205
265
225
198
186
189
265
486
460
309
104
292
244
112
84
331
219
275
383
206
318
467
243
300
376
248
146
83
408
348
303
171
197
230
270
496
442
177
372
393
272
59
270
441
219
63
295
354
354
94
119
58
449
295
111
406
493
248
381
68
495
364
492
235
218
61
462
287
410
363
86
133
77
407
259
108
237
352
114
205
130
313
143
119
371
132
173
422
280
260
336
488
129
480
145
449
106
298
125
335
168
79
55
328
338
182
450
487
432
246
463
114
336
347
328
375
485
248
283
286
324
98
121
211
123
317
482
189
480
53
107
197
474
200
369
466
77
224
432
183
281
251
83
385
353
347
375
473
178
291
130
407
238
70
370
361
484
351
58
252
477
458
477
397
410
251
247
107
406
229
359
76
387
207
262
152
212
253
448
365
152
402
80
134
343
120
305
500
375
410
274
131
59
90
237
279
282
307
209
117
123
370
424
217
408
133
108
110
68
107
315
61
194
252
351
416
130
479
350
277
211
268
202
237
434
420
170
134
252
398
115
493
457
113
190
454
123
283
130
98
115
394
392
449
144
150
424
191
213
478
344
52
166
348
476
333
113
88
369
86
361
213
487
229
407
449
447
109
215
149
332
486
458
339
241
172
322
312
55
143
351
72
134
98
406
239
85
394
472
275
456
161
373
233
421
440
341
137
381
69
419
484
402
337
495
410
403
494
142
59
398
431
95
98
491
366
204
386
56
350
268
449
84
439
240
327
339
487
245
306
63
142
393
474
428
147
418
209
259
463
181
270
172
366
114
100
307
341
365
366
388
192
230
164
357
361
318
340
251
372
247
270
333
211
185
466
251
145
195
195
365
274
133
356
259
162
491
75
159
278
104
252
488
465
438
465
426
435
53
74
365
420
238
52
179
469
397
313
351
279
51
308
193
169
274
413
239
324
246
313
254
83
398
143
248
120
121
272
309
401
129
339
449
62
249
341
310
384
495
204
454
355
140
114
267
235
167
74
277
79
306
210
183
134
360
61
343
165
356
203
263
279
186
233
110
496
477
362
146
415
377
418
313
385
235
75
422
116
125
111
149
186
481
87
364
216
493
137
262
121
409
93
311
296
188
213
254
105
93
274
187
131
100
195
422
130
358
428
219
132
486
254
301
64
329
207
476
382
475
395
134
122
292
374
304
236
240
469
70
313
358
75
198
124
168
79
188
373
130
75
281
389
180
148
233
376
164
189
345
212
108
313
452
152
176
447
348
247
257
361
312
472
387
410
438
79
157
433
204
142
483
307
349
216
133
161
467
498
193
250
323
249
199
445
296
255
420
66
65
339
75
445
198
260
252
203
51
472
178
309
317
118
154
304
465
488
179
469
452
413
416
213
226
160
52
109
310
300
215
307
363
312
67
372
405
415
491
378
240
143
494
187
420
251
54
221
436
290
401
431
267
158
117
345
276
167
240
66
337
65
260
196
385
344
381
372
226
463
413
337
377
459
381
500
150
188
304
177
441
335
214
78
241
326
254
445
261
240
144
129
72
442
373
205
244
268
218
499
70
135
198
163
451
233
131
158
334
347
310
56
149
295
421
379
261
231
103
384
348
218
55
229
323
326
416
478
258
60
400
496
101
182
212
196
187
159
397
313
69
52
420
311
365
472
322
318
83
64
75
303
229
332
248
394
123
333
247
465
268
393
451
306
106
484
492
148
229
138
61
348
248
91
445
377
453
142
350
317
410
444
321
188
413
105
369
65
68
370
432
247
225
427
182
300
371
243
499
370
254
457
497
346
282
446
377
278
472
183
439
220
81
421
427
167
230
255
436
397
430
325
179
214
410
52
143
333
225
215
83
360
498
497
301
91
247
175
77
380
304
282
160
360
334
407
418
470
454
447
487
479
287
157
215
318
69
213
363
332
454
493
189
295
86
441
431
127
278
298
492
188
128
433
316
306
323
163
427
463
372
301
269
369
278
264
279
128
148
227
494
116
170
468
346
377
481
214
242
97
378
66
393
363
262
199
390
242
449
241
276
180
321
88
51
135
475
468
465
167
245
442
58
477
293
283
410
473
329
329
373
339
173
300
67
166
235
329
297
170
455
351
463
215
428
337
275
488
372
205
425
435
329
447
473
284
131
77
93
481
169
478
90
295
483
81
495
404
213
108
487
150
274
74
353
143
391
174
321
150
115
432
308
190
332
434
153
201
105
168
435
290
444
63
187
394
277
73
302
382
362
170
232
102
119
216
108
464
357
387
409
348
474
268
202
359
246
272
499
217
215
218
148
88
437
248
102
238
366
282
191
486
347
222
100
316
487
83
266
105
113
429
144
389
340
354
267
177
345
458
354
139
51
468
50
88
172
446
198
271
118
240
487
182
76
396
110
412
201
311
381
425
439
442
370
211
462
116
492
156
255
70
486
412
488
307
175
311
210
205
435
399
414
160
290
101
202
111
124
151
140
126
328
124
272
92
338
144
126
166
71
491
392
350
86
306
299
362
399
497
474
107
256
497
192
334
208
421
451
360
290
192
387
312
417
112
319
235
271
480
68
388
339
305
226
328
239
330
281
298
164
243
462
454
274
292
302
136
163
309
386
381
405
398
434
130
451
53
420
148
183
266
229
66
216
477
74
430
278
445
174
204
397
62
312
50
106
405
108
264
92
293
499
103
185
248
99
61
201
325
67
470
208
192
205
417
171
235
303
54
120
161
226
139
280
257
285
76
252
238
108
69
335
323
281
366
289
253
144
171
124
365
66
404
183
234
108
346
341
253
376
152
396
379
307
115
435
241
212
224
406
319
136
448
431
493
403
427
442
441
375
250
387
253
446
131
167
218
201
182
301
492
205
92
147
271
142
130
179
487
228
354
93
267
240
146
367
56
428
269
228
386
253
223
180
351
201
438
266
409
373
89
457
204
118
321
499
325
125
417
389
479
379
303
396
462
113
263
233
225
135
368
88
325
226
444
85
490
335
467
78
206
454
247
69
408
498
488
460
490
388
403
235
164
418
183
259
405
400
305
343
390
478
205
217
289
71
254
477
99
305
386
126
265
417
374
193
231
273
261
126
231
106
130
179
182
92
78

## Arithmetic operators

In [144]:
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

In [145]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int32

In [146]:
added_data = dataframe + 100

In [147]:
added_data

Youtuber Name
Eric Patel            168
Cynthia Harrington    175
Amanda Walker         382
Jessica Nelson MD     402
Matthew Sherman       229
                     ...
John Rasmussen        230
Lisa Burke            279
Steve Diaz            282
Austin Tate           192
Amit Kumar Singh      178
Name: Total Videos, Length: 5001, dtype: int32

In [148]:
diff_data = added_data - 50

In [149]:
diff_data

Youtuber Name
Eric Patel            118
Cynthia Harrington    125
Amanda Walker         332
Jessica Nelson MD     352
Matthew Sherman       179
                     ...
John Rasmussen        180
Lisa Burke            229
Steve Diaz            232
Austin Tate           142
Amit Kumar Singh      128
Name: Total Videos, Length: 5001, dtype: int32

In [150]:
diff_data * 2

Youtuber Name
Eric Patel            236
Cynthia Harrington    250
Amanda Walker         664
Jessica Nelson MD     704
Matthew Sherman       358
                     ...
John Rasmussen        360
Lisa Burke            458
Steve Diaz            464
Austin Tate           284
Amit Kumar Singh      256
Name: Total Videos, Length: 5001, dtype: int32

## Relational operators in series

In [151]:
diff_data > 400

Youtuber Name
Eric Patel            False
Cynthia Harrington    False
Amanda Walker         False
Jessica Nelson MD     False
Matthew Sherman       False
                      ...
John Rasmussen        False
Lisa Burke            False
Steve Diaz            False
Austin Tate           False
Amit Kumar Singh      False
Name: Total Videos, Length: 5001, dtype: bool

In [152]:
diff_data

Youtuber Name
Eric Patel            118
Cynthia Harrington    125
Amanda Walker         332
Jessica Nelson MD     352
Matthew Sherman       179
                     ...
John Rasmussen        180
Lisa Burke            229
Steve Diaz            232
Austin Tate           142
Amit Kumar Singh      128
Name: Total Videos, Length: 5001, dtype: int32

In [153]:
400 > diff_data

Youtuber Name
Eric Patel            True
Cynthia Harrington    True
Amanda Walker         True
Jessica Nelson MD     True
Matthew Sherman       True
                      ...
John Rasmussen        True
Lisa Burke            True
Steve Diaz            True
Austin Tate           True
Amit Kumar Singh      True
Name: Total Videos, Length: 5001, dtype: bool

In [154]:
200 > diff_data

Youtuber Name
Eric Patel             True
Cynthia Harrington     True
Amanda Walker         False
Jessica Nelson MD     False
Matthew Sherman        True
                      ...
John Rasmussen         True
Lisa Burke            False
Steve Diaz            False
Austin Tate            True
Amit Kumar Singh       True
Name: Total Videos, Length: 5001, dtype: bool

## Boolean indexing

#### In order to perform the important analysis on the column value, where in a specific index value IF it is meeting a condition that we get true over their else we get false when the condition is not meeting for that specific index.

##### Boolean index --> True --> condition is true
##### Boolean index --> False --> condition is not true

In [155]:
avg

500     19.1
451     28.0
1713    28.0
171     28.0
3704    28.0
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [156]:
### Which youtubers are having average video length greater than 24 minutes

avg > 24

500     False
451      True
1713     True
171      True
3704     True
        ...
2748     True
925      True
364      True
1467     True
361      True
Name: Avg Video Length (min), Length: 5000, dtype: bool

In [157]:
avg[avg>24]

451     28.0
1713    28.0
171     28.0
3704    28.0
4794    24.1
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 2382, dtype: float64

In [158]:
avg[avg>24].size

2382

In [159]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int32

In [160]:
dataframe > 120

Youtuber Name
Eric Patel            False
Cynthia Harrington    False
Amanda Walker          True
Jessica Nelson MD      True
Matthew Sherman        True
                      ...
John Rasmussen         True
Lisa Burke             True
Steve Diaz             True
Austin Tate           False
Amit Kumar Singh      False
Name: Total Videos, Length: 5001, dtype: bool

In [161]:
dataframe[dataframe>120]

Youtuber Name
Amanda Walker        282
Jessica Nelson MD    302
Matthew Sherman      129
Richard Arnold       494
Stephanie Potter     133
                    ...
Howard Phelps        126
Sharon Graham        231
John Rasmussen       130
Lisa Burke           179
Steve Diaz           182
Name: Total Videos, Length: 4174, dtype: int32

In [162]:
dataframe[dataframe > 150].size

3839

# Plotting graphs in pandas

#### For plotting graphs in pandas, we require plot() --> df.plot()

#### kind parameter --> it decides that what kind of graph you want to plot

In [163]:
avg

500     19.1
451     28.0
1713    28.0
171     28.0
3704    28.0
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [164]:
avg.plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [165]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington     75
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Amit Kumar Singh       78
Name: Total Videos, Length: 5001, dtype: int32

In [166]:
dataframe.sort_values(ascending=False)

Youtuber Name
Julian Gutierrez     500
Dominique Martin     500
Jeremiah Freeman     500
William Jones        500
Paul Silva           500
                    ...
Michael Sims          50
Brittany Gross        50
Jay Johnson           50
Ronald Williams       50
Christy Hernandez     50
Name: Total Videos, Length: 5001, dtype: int32

In [167]:
dataframe.sort_values(ascending=False).head(15)

Youtuber Name
Julian Gutierrez    500
Dominique Martin    500
Jeremiah Freeman    500
William Jones       500
Paul Silva          500
Eric Riley          500
Philip Adkins       500
Miguel Ross         500
David Santiago      500
Amy Russo           500
Brian Thompson      499
James Hall          499
Kyle Martin         499
Sara Short          499
Tina Atkinson       499
Name: Total Videos, dtype: int32

In [168]:
dataframe.sort_values(ascending=False).head(15).plot(kind='bar')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [169]:
dataframe.sort_values(ascending=False).sample(15)

Youtuber Name
Jonathan White    218
Luis Rivera       216
Rachel Sparks     119
Paul Craig DDS    480
Andrea Ramsey     203
Wendy Mathews     467
Sara Graham       332
Craig Young       360
Michael Murray    257
Jasmine Howard    233
Derrick Harper    232
James Rose        448
Thomas Johnson    331
Kayla Fischer     246
Michael Lewis     257
Name: Total Videos, dtype: int32

In [170]:
dataframe.sort_values(ascending=False).sample(15).plot(kind='bar')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [171]:
dataframe.sort_values(ascending=False).sample(15).plot(kind='pie')

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.