In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.5.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tarkeshwar\desktop\abhishek\technical skills\tutedude\gen ai\machine learning\prerequisites\module 8_pandas\pandas\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\tarkeshwar\desktop\abhishek\technical skills\tutedude\gen ai\machine learning\prerequisites\module 8_pandas\pandas\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.6 MB 365.3 kB/s eta 0:00:25
   -- ------------------------------------- 0.5/9.6 MB 365.3 kB/s eta 0:00:25
   -- ------------------------------------- 0.5/9.6 MB 365.3 kB/s eta 0:00:25
   --- ------------------------------------ 0.8/9.6 MB 416.5 kB/s eta 0:00:22
   --- ------------------------------------ 0.8/9.6 MB 416.5 kB/s eta 0:00:22
   ---- ----------------------------------- 1.0/9.6 MB 463.8 kB/s eta 0:00:19
   ---- ----------------------------------- 1.0/9.6 MB 463.8 kB/s eta 0:00:19
   ---- ----------------------------------- 1.0/9.6 MB 463.8 kB/s eta 0:00:19
   ---- ----------------------------------- 1.0/9.6 MB 463.8 kB/s eta 0:00:19
   ---- ----------------------------------- 1.0/9.6 MB 463.8 kB/s eta 0:00:19
   ---- ----------------------------------- 1.0/9.6 MB 463.8 kB/s eta 0:00:19
   ----- ---------------------------------- 1.3/9.6 MB 357.6 kB/s eta 0:00:24
   ----- ---------------------------------- 1.3/9.6 MB 357.6 kB/s eta 0:00:24
   ------ --------------------------------- 1.6/9.6 MB 391.5 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.6 MB 391.5 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.6 MB 391.5 kB/s eta 0:00:21
   ------- -------------------------------- 1.8/9.6 MB 408.9 kB/s eta 0:00:20
   ------- -------------------------------- 1.8/9.6 MB 408.9 kB/s eta 0:00:20
   ------- -------------------------------- 1.8/9.6 MB 408.9 kB/s eta 0:00:20
   -------- ------------------------------- 2.1/9.6 MB 408.0 kB/s eta 0:00:19
   -------- ------------------------------- 2.1/9.6 MB 408.0 kB/s eta 0:00:19
   -------- ------------------------------- 2.1/9.6 MB 408.0 kB/s eta 0:00:19
   --------- ------------------------------ 2.4/9.6 MB 414.9 kB/s eta 0:00:18
   --------- ------------------------------ 2.4/9.6 MB 414.9 kB/s eta 0:00:18
   ---------- ----------------------------- 2.6/9.6 MB 422.5 kB/s eta 0:00:17
   ---------- ----------------------------- 2.6/9.6 MB 422.5 kB/s eta 0:00:17
   ---------- ----------------------------- 2.6/9.6 MB 422.5 kB/s eta 0:00:17
   ----------- ---------------------------- 2.9/9.6 MB 426.7 kB/s eta 0:00:16
   ----------- ---------------------------- 2.9/9.6 MB 426.7 kB/s eta 0:00:16
   ------------- -------------------------- 3.1/9.6 MB 433.2 kB/s eta 0:00:15
   ------------- -------------------------- 3.1/9.6 MB 433.2 kB/s eta 0:00:15
   ------------- -------------------------- 3.1/9.6 MB 433.2 kB/s eta 0:00:15
   ------------- -------------------------- 3.1/9.6 MB 433.2 kB/s eta 0:00:15
   ------------- -------------------------- 3.1/9.6 MB 433.2 kB/s eta 0:00:15
   -------------- ------------------------- 3.4/9.6 MB 416.8 kB/s eta 0:00:15
   -------------- ------------------------- 3.4/9.6 MB 416.8 kB/s eta 0:00:15
   --------------- ------------------------ 3.7/9.6 MB 423.4 kB/s eta 0:00:15
   --------------- ------------------------ 3.7/9.6 MB 423.4 kB/s eta 0:00:15
   --------------- ------------------------ 3.7/9.6 MB 423.4 kB/s eta 0:00:15
   ---------------- ----------------------- 3.9/9.6 MB 431.0 kB/s eta 0:00:14
   ---------------- ----------------------- 3.9/9.6 MB 431.0 kB/s eta 0:00:14
   ----------------- ---------------------- 4.2/9.6 MB 439.1 kB/s eta 0:00:13
   ----------------- ---------------------- 4.2/9.6 MB 439.1 kB/s eta 0:00:13
   ------------------ --------------------- 4.5/9.6 MB 446.3 kB/s eta 0:00:12
   ------------------ --------------------- 4.5/9.6 MB 446.3 kB/s eta 0:00:12
   ------------------- -------------------- 4.7/9.6 MB 450.3 kB/s eta 0:00:11
   ------------------- -------------------- 4.7/9.6 MB 450.3 kB/s eta 0:00:11
   ------------------- -------------------- 4.7/9.6 MB 450.3 kB/s eta 0:00:11
   -------------------- ------------------- 5.0/9.6 MB 448.7 kB/s eta 0:00:11
   -------------------- ------------------- 5.0/9.6 MB 448.7 kB/s eta 0:00:11
   -------------------- ------------------- 5.0/9.6 MB 448.7 kB/s eta 0:00:11
   -------------------- ------------------- 5.0/9.6 MB 448.7 kB/s eta 0:00:11
   -------------------- ------------------- 5.0/9.6 MB 448.7 kB/s eta 0:00:11
   --------------------- ------------------ 5.2/9.6 MB 433.7 kB/s eta 0:00:11
   --------------------- ------------------ 5.2/9.6 MB 433.7 kB/s eta 0:00:11
   --------------------- ------------------ 5.2/9.6 MB 433.7 kB/s eta 0:00:11
   ---------------------- ----------------- 5.5/9.6 MB 435.5 kB/s eta 0:00:10
   ---------------------- ----------------- 5.5/9.6 MB 435.5 kB/s eta 0:00:10
   ---------------------- ----------------- 5.5/9.6 MB 435.5 kB/s eta 0:00:10
   ---------------------- ----------------- 5.5/9.6 MB 435.5 kB/s eta 0:00:10
   ----------------------- ---------------- 5.8/9.6 MB 429.8 kB/s eta 0:00:10
   ----------------------- ---------------- 5.8/9.6 MB 429.8 kB/s eta 0:00:10
   ------------------------- -------------- 6.0/9.6 MB 434.7 kB/s eta 0:00:09
   ------------------------- -------------- 6.0/9.6 MB 434.7 kB/s eta 0:00:09
   -------------------------- ------------- 6.3/9.6 MB 437.5 kB/s eta 0:00:08
   -------------------------- ------------- 6.3/9.6 MB 437.5 kB/s eta 0:00:08
   -------------------------- ------------- 6.3/9.6 MB 437.5 kB/s eta 0:00:08
   --------------------------- ------------ 6.6/9.6 MB 442.5 kB/s eta 0:00:07
   ---------------------------- ----------- 6.8/9.6 MB 449.4 kB/s eta 0:00:07
   ---------------------------- ----------- 6.8/9.6 MB 449.4 kB/s eta 0:00:07
   ---------------------------- ----------- 6.8/9.6 MB 449.4 kB/s eta 0:00:07
   ---------------------------- ----------- 6.8/9.6 MB 449.4 kB/s eta 0:00:07
   ---------------------------- ----------- 6.8/9.6 MB 449.4 kB/s eta 0:00:07
   ----------------------------- ---------- 7.1/9.6 MB 436.3 kB/s eta 0:00:06
   ----------------------------- ---------- 7.1/9.6 MB 436.3 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.6 MB 436.5 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.6 MB 436.5 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.6 MB 436.5 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.6 MB 436.5 kB/s eta 0:00:06
   ------------------------------ --------- 7.3/9.6 MB 436.5 kB/s eta 0:00:06
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.6/9.6 MB 427.3 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.6 MB 355.2 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.6 MB 355.2 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.6 MB 355.2 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.6 MB 355.2 kB/s eta 0:00:05
   -------------------------------- ------- 7.9/9.6 MB 355.2 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.6 MB 351.9 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.6 MB 351.9 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.6 MB 351.9 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.6 MB 351.9 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.6 MB 351.9 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.6 MB 351.9 kB/s eta 0:00:05
   --------------------------------- ------ 8.1/9.6 MB 351.9 kB/s eta 0:00:05
   ---------------------------------- ----- 8.4/9.6 MB 341.3 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.6 MB 341.3 kB/s eta 0:00:04
   ----------------------------------- ---- 8.7/9.6 MB 344.2 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.6 MB 344.2 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.6 MB 344.2 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.6 MB 344.2 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.6 MB 344.5 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.6 MB 344.5 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.6 MB 344.5 kB/s eta 0:00:03
   ------------------------------------ --- 8.9/9.6 MB 344.5 kB/s eta 0:00:03
   -------------------------------------- - 9.2/9.6 MB 343.8 kB/s eta 0:00:02
   -------------------------------------- - 9.2/9.6 MB 343.8 kB/s eta 0:00:02
   ---------------------------------------  9.4/9.6 MB 346.8 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 346.8 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 346.8 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 346.8 kB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 344.0 kB/s eta 0:00:00
Using cached numpy-2.5.3-cp313-cp313-win_amd64.whl (12.6 MB)
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.5.3 pandas-3.0.6 tzdata-2026.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd

## Pandas Series is a column of data in a table like in excel or google sheets with labels called as indexes attached to each value.

In [3]:
pd.Series(data=[40,50,60], index=['Bread','Milk','Butter'])

Bread     40
Milk      50
Butter    60
dtype: int64

In [4]:
pd.Series(data=[40,50,60], index=['Bread','Milk','Butter'], name='Price of grocery items')

Bread     40
Milk      50
Butter    60
Name: Price of grocery items, dtype: int64

#### Series is a 1-d array that can hold any type of data like integers, floats, boolean, string (objects), mixed data types

## Data type ---> integers --> data in a Series (column) --> Quantity of items in the stock
## Data type ---> Float ---> data in a Series (column) ---> Price or product ratings
## Data type ---> String --> data in a Series (column) ---> Product name
## Data type ---> boolean --> data in a Series (column) ---> Is item in stock ?
## Data type ---> Data/ Time --> data in a Series (column) ---> Expiry dates or sale dates
## Mixed type ---> Milk, 40, True

## Creating a Series in Multiple ways :-
#### 1. List
#### 2. NumPy array
#### 3. Dictionary
#### 4. Custom index
#### 5. Scalar value

In [5]:
## Series from list:-

country=['India','China','USA','Pakistan']

pd.Series(country)

0       India
1       China
2         USA
3    Pakistan
dtype: str

In [6]:
batsman_runs = [48,64,72,98,114,183]


pd.Series(batsman_runs)
# pd.Series(batsman_runs, dtype='int32')

0     48
1     64
2     72
3     98
4    114
5    183
dtype: int64

In [7]:
subject_names = ['Maths','Physics','Chemistry','Biology','English']

subject_marks = [48,92,64,35,98]

pd.Series(data=subject_marks, index=subject_names, name='Subject marks data', dtype='int32')

Maths        48
Physics      92
Chemistry    64
Biology      35
English      98
Name: Subject marks data, dtype: int32

In [8]:
### Creating a Series using a NumPy array

values = np.arange(10,21)
pd.Series(values)

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

In [9]:
## Dictionary to Series

## Dictionary is another data structure that stores the data in a key:value pair and 
## just because it stores the data in a key:value pair so we don't have to explicitly mention the index.

In [10]:
data_items = {'Marks':78, 'English':92, 'Physics':88, 'Chemistry':64}
pd.Series(data_items)

Marks        78
English      92
Physics      88
Chemistry    64
dtype: int64

In [11]:
## custom index to series

values = [1,2,3,4,5]
pd.Series(data=values, index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [12]:
## Scalar value inside a Series 

pd.Series(4,index=['a','b','c','d','e'])

a    4
b    4
c    4
d    4
e    4
dtype: int64

## read_csv() ---> 90% is being used --> this function reads the content from the csv file in pandas dataframe format so that we can perform the operations on the data or we can perform effective analysis.

In [13]:
Data = pd.read_csv('C:/Users/Tarkeshwar/Desktop/ABHISHEK/Technical skills/Tutedude/Gen AI/Machine Learning/Prerequisites/Module 8_Pandas/Pandas/youtube_2025_dataset_202504061614.csv')

In [14]:
Data

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [15]:
# 2nd way to read
df = pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [16]:
df

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [17]:
## DataFrame --> Combination of multiple Series (Series means a single column)

In [18]:
## converting data frame to Series --> use squeeze parameter --> it make sure that the data is in Series format

In [19]:
pd.read_csv('youtube_one_column.csv')

                     Channel Name
0                 Smith-Ross Labs
1                Sandoval PLC Hub
2     Jones, Moore and Ho Network
3            Mitchell-Hooper Labs
4              Wilson LLC Studios
...                           ...
4995        Flores-Daniel Studios
4996     Spencer and Sons Studios
4997       Obrien-Roberts Studios
4998                 King Ltd Hub
4999            Henry Ltd Studios

[5000 rows x 1 columns]

In [20]:
type(pd.read_csv('youtube_one_column.csv'))

pandas.DataFrame

In [21]:
## to convert data frame into Series :-

df = pd.read_csv('youtube_one_column.csv').squeeze('columns')

In [22]:
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

In [23]:
type(df)

pandas.Series

In [24]:
pd.read_csv('youtube_two_column.csv')

           Youtuber Name  Total Videos
0             Eric Patel            68
1     Cynthia Harrington           128
2          Amanda Walker           282
3      Jessica Nelson MD           302
4        Matthew Sherman           129
...                  ...           ...
4995       Jasmine Smith           106
4996      John Rasmussen           130
4997          Lisa Burke           179
4998          Steve Diaz           182
4999         Austin Tate            92

[5000 rows x 2 columns]

In [25]:
## index_col

In [26]:
dataframe = pd.read_csv('youtube_two_column.csv', index_col='Youtuber Name').squeeze('columns')

In [27]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int64

In [28]:
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

### Attribute in Series

### 1) .values --> representing only the values of the given series
### 2) .index --> returns only the index values from the given column
### 3) .dtype --> it provides the idea about the data type of the values that you are storing
### 4) .size --> this attribute provides the idea about the total number of rows inside the dataset
### 5) .shape --> this attribute provides the idea about the row, column information
### 6) .ndim --> this attribute provides the idea about the dimention of the given dataset
### 7) .name --> this attribute provides the idea about the name of the series
### 8) .is_unique --> this provides us with the idea about whether if unique values are there or not inside the column

In [29]:
df.values

<StringArray>
[                    'Smith-Ross Labs',                    'Sandoval PLC Hub',
         'Jones, Moore and Ho Network',                'Mitchell-Hooper Labs',
                  'Wilson LLC Studios',                   'Myers Ltd Network',
                   'Huber Inc Network',              'Baxter-Collins Studios',
                   'Morrow-Abbott Hub',               'Jackson Group Network',
 ...
                     'Cole-Sharp Labs', 'Sherman, Mcgee and Phillips Studios',
                      'Baker-Hill Hub',    'Francis, Davis and Jones Network',
     'Whitaker, Horn and Escobar Labs',               'Flores-Daniel Studios',
            'Spencer and Sons Studios',              'Obrien-Roberts Studios',
                        'King Ltd Hub',                   'Henry Ltd Studios']
Length: 5000, dtype: str

In [30]:
dataframe.values

array([ 68, 128, 282, ..., 179, 182,  92], shape=(5000,))

In [31]:
dataframe.index

Index(['Eric Patel', 'Cynthia Harrington', 'Amanda Walker',
       'Jessica Nelson MD', 'Matthew Sherman', 'Anna Berry', 'Richard Arnold',
       'Stephanie Potter', 'Teresa Aguirre', 'Anne Adkins',
       ...
       'Erin Bradley', 'Brooke Perez', 'Nicholas Jordan', 'Howard Phelps',
       'Sharon Graham', 'Jasmine Smith', 'John Rasmussen', 'Lisa Burke',
       'Steve Diaz', 'Austin Tate'],
      dtype='str', name='Youtuber Name', length=5000)

In [32]:
dataframe.dtype

dtype('int64')

In [33]:
df.dtype

In [34]:
dataframe = dataframe.astype('int32')

In [35]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [36]:
dataframe.size

5000

In [37]:
dataframe.shape

(5000,)

In [38]:
dataframe.ndim

1

In [39]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [40]:
dataframe.name

'Total Videos'

In [41]:
dataframe.is_unique

False

In [42]:
pd.Series([1,2,3,4,5]).is_unique

True

## Series methods

#### 1) head() ---> provides the top preview of data as the top 5 rows of the dataframe or Series. It is quite helpful with providing the preview of the dataset and if we want to preview top 10 rows then we can pass 10 as the argument or for top 7 rows we can pass 7 as an argument. 

#### 2) tail() ---> provides the bottom preview of data as the bottom 5 rows

#### for e.g. --> dataset --> salary column --> top 5 rows --> salary --> 7 lpa ---> top 10 ---> top 15 ,,, tail() ---> bottom 5 rows ---> salary --> 4 lpa, 9 lpa

#### 3) sample() --> provides any custom row from the dataset for us to preview it.

#### 4) value_counts() --> it provides the idea about the count of the values (categorical values), if i am having a column where the categorical value count i want to calculate then i can go with value_counts()

#### 5) sort_values() --> this method sorts the value in an ascending manner. It can be useful for us for the numerical columns. you can even sort the values in descending manner as well.

#### 6) sort_index() --> this method sorts the index of the dataset.

In [43]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [44]:
dataframe.head()

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Name: Total Videos, dtype: int32

In [45]:
dataframe.head(9)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Anna Berry             98
Richard Arnold        494
Stephanie Potter      133
Teresa Aguirre        316
Name: Total Videos, dtype: int32

In [46]:
dataframe.head(21)

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
Anna Berry             98
Richard Arnold        494
Stephanie Potter      133
Teresa Aguirre        316
Anne Adkins           140
David Clark            52
Kathleen Weeks        149
Melissa Kennedy        53
Kimberly Brown        299
Jennifer Martinez     383
Elizabeth Wright       79
Elijah Ruiz           373
Thomas Roberts         59
Julian Gutierrez      500
Sheila Rivera         332
Crystal Vargas        133
Name: Total Videos, dtype: int32

In [47]:
dataframe.tail()

Youtuber Name
Jasmine Smith     106
John Rasmussen    130
Lisa Burke        179
Steve Diaz        182
Austin Tate        92
Name: Total Videos, dtype: int32

In [48]:
df.head()

0                Smith-Ross Labs
1               Sandoval PLC Hub
2    Jones, Moore and Ho Network
3           Mitchell-Hooper Labs
4             Wilson LLC Studios
Name: Channel Name, dtype: str

In [49]:
df.tail()

4995       Flores-Daniel Studios
4996    Spencer and Sons Studios
4997      Obrien-Roberts Studios
4998                King Ltd Hub
4999           Henry Ltd Studios
Name: Channel Name, dtype: str

In [50]:
df.tail(11)

4989                   Knight and Sons Labs
4990                        Cole-Sharp Labs
4991    Sherman, Mcgee and Phillips Studios
4992                         Baker-Hill Hub
4993       Francis, Davis and Jones Network
4994        Whitaker, Horn and Escobar Labs
4995                  Flores-Daniel Studios
4996               Spencer and Sons Studios
4997                 Obrien-Roberts Studios
4998                           King Ltd Hub
4999                      Henry Ltd Studios
Name: Channel Name, dtype: str

In [51]:
df.sample()

1955    Davis LLC Labs
Name: Channel Name, dtype: str

In [52]:
df.sample(5)

878     Moore, Hamilton and Burton Hub
4587                Parker LLC Studios
2007                   Shah Group Labs
3425                 Smith LLC Network
926                Richards-Wright Hub
Name: Channel Name, dtype: str

In [53]:
youtube = pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [54]:
youtube

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [55]:
avg = youtube['Avg Video Length (min)']

In [56]:
avg

0       24.8
1       22.9
2       24.0
3       24.6
4       24.6
        ...
4995    22.0
4996    26.3
4997    25.2
4998    24.5
4999    25.2
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [57]:
type(avg)

pandas.Series

In [58]:
avg.value_counts()

Avg Video Length (min)
24.1    276
23.8    264
23.9    256
24.2    253
24.0    251
       ...
19.9      1
27.3      1
28.0      1
21.0      1
20.7      1
Name: count, Length: 78, dtype: int64

In [59]:
df

0                   Smith-Ross Labs
1                  Sandoval PLC Hub
2       Jones, Moore and Ho Network
3              Mitchell-Hooper Labs
4                Wilson LLC Studios
                   ...
4995          Flores-Daniel Studios
4996       Spencer and Sons Studios
4997         Obrien-Roberts Studios
4998                   King Ltd Hub
4999              Henry Ltd Studios
Name: Channel Name, Length: 5000, dtype: str

In [60]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [61]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [62]:
## parameter --> ascending = False (sorting --? descending)

avg.sort_values(ascending=False)

361     28.9
1467    28.4
364     28.3
925     28.1
2748    28.0
        ...
3704    20.7
171     20.6
1713    19.9
451     19.3
500     19.1
Name: Avg Video Length (min), Length: 5000, dtype: float64

## Method chaining --> we will use multiple methods together to get the required value in a way the first method's output will be second method's input then second's method output will be third method's input

In [64]:
avg.sort_values(ascending=False).head(1)

361    28.9
Name: Avg Video Length (min), dtype: float64

In [65]:
avg.sort_values(ascending=False).head(1).values[0]

np.float64(28.9)

In [83]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [84]:
### In order to make a change in your data permanent --> inplace parameter

In [85]:
avg.sort_values()

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [86]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [88]:
avg.sort_values(inplace=True)

In [89]:
avg

500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64

In [90]:
average_data = avg.copy

In [91]:
average_data

<bound method NDFrame.copy of 500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64>

In [93]:
average_data

<bound method NDFrame.copy of 500     19.1
451     19.3
1713    19.9
171     20.6
3704    20.7
        ...
2748    28.0
925     28.1
364     28.3
1467    28.4
361     28.9
Name: Avg Video Length (min), Length: 5000, dtype: float64>

In [94]:
dataframe

Youtuber Name
Eric Patel             68
Cynthia Harrington    128
Amanda Walker         282
Jessica Nelson MD     302
Matthew Sherman       129
                     ...
Jasmine Smith         106
John Rasmussen        130
Lisa Burke            179
Steve Diaz            182
Austin Tate            92
Name: Total Videos, Length: 5000, dtype: int32

In [95]:
dataframe.sort_index()

Youtuber Name
Aaron Archer        136
Aaron Bishop        151
Aaron Brown          51
Aaron Burns         314
Aaron Carrillo      210
                   ...
Zachary Phillips    478
Zachary Russell      81
Zachary Shelton     446
Zoe Peterson         78
Zoe Smith            83
Name: Total Videos, Length: 5000, dtype: int32